const fs = require('fs');

const filePath = '/Volumes/T7/Droword/Droword/Localizable.xcstrings';
const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

// Complete French translation map
const translations = {
  "": "",
  " %@": " %@",
  " %@ ": " %@ ",
  "\u2014": "\u2014",
  "\u00b7": "\u00b7",
  "\"%@\" updated with translation": "\u00ab %@ \u00bb mis \u00e0 jour avec la traduction",
  "\u00ab%@\u00bb is already in your dictionary.": "\u00ab %@ \u00bb est d\u00e9j\u00e0 dans votre dictionnaire.",
  "(%@)": "(%@)",
  "[%@]": "[%@]",
  "/%@/": "/%@/",
  "/\u02ccs\u025br.\u0259n\u02c8d\u026ap.\u026a.ti/": "/\u02ccs\u025br.\u0259n\u02c8d\u026ap.\u026a.ti/",
  "/ot\u0283a/": "/ot\u0283a/",
  "%@ ": "%@ ",
  "%@ (%lld)": "%@ (%lld)",
  "%@ / month": "%@ / mois",
  "%@ / year": "%@ / an",
  "%@ with Droword": "%@ avec Droword",
  "%@, %@": "%@, %@",
  "%@/mo": "%@/mois",
  "%lld": "%lld",
  "%lld / day": "%lld / jour",
  "%lld added": "%lld ajout\u00e9(s)",
  "%lld d": "%lld j",
  "%lld h": "%lld h",
  "%lld min": "%lld min",
  "%lld of %lld completed": "%lld sur %lld termin\u00e9(s)",
  "%lld words at %lld per week. You're becoming a true linguist.": "%lld mots \u00e0 %lld par semaine. Vous devenez un vrai linguiste.",
  "%lld words in less than a month \u2014 impressive!": "%lld mots en moins d\u2019un mois \u2014 impressionnant !",
  "%lld words! You've reached legendary status.": "%lld mots ! Vous avez atteint le statut l\u00e9gendaire.",
  "%lld-day streak!": "%lld jours cons\u00e9cutifs !",
  "%lld/%lld": "%lld/%lld",
  "%lld/40": "%lld/40",
  "%lld%%": "%lld%%",
  "%lldh %lldm": "%lldh %lldmin",
  "%lldm": "%lldmin",
  "%lldm studied": "%lldmin \u00e9tudi\u00e9es",
  "+%lld more": "+%lld de plus",
  "\u2b50": "\u2b50",
  "\ud83d\udca1": "\ud83d\udca1",
  "\ud83d\udcda": "\ud83d\udcda",
  "\ud83d\udd25": "\ud83d\udd25",
  "1 / week": "1 / semaine",
  "2/7": "2/7",
  "4 / day": "4 / jour",
  "7-day streak": "7 jours cons\u00e9cutifs",
  "10 / day": "10 / jour",
  "30-day streak": "30 jours cons\u00e9cutifs",
  "100 days. %lld words. Unstoppable.": "100 jours. %lld mots. Inarr\u00eatable.",
  "100-day streak": "100 jours cons\u00e9cutifs",
  "A": "A",
  "A \u2192 Z": "A \u2192 Z",
  "A few minutes now \u2014 your future self will thank you!": "Quelques minutes maintenant \u2014 votre futur vous remerciera !",
  "A full week of learning! %lld words and counting.": "Une semaine compl\u00e8te d\u2019apprentissage ! %lld mots et ce n\u2019est pas fini.",
  "A quick review keeps words fresh. Come back?": "Une petite r\u00e9vision garde les mots frais. On s\u2019y remet ?",
  "A scene from a movie?": "Une sc\u00e8ne de film ?",
  "A whole month. %lld words in your dictionary.": "Un mois entier. %lld mots dans votre dictionnaire.",
  "A word a day": "Un mot par jour",
  "Accept 5 suggested words": "Accepter 5 mots sugg\u00e9r\u00e9s",
  "Accept 20 suggested words": "Accepter 20 mots sugg\u00e9r\u00e9s",
  "Accept 50 suggested words": "Accepter 50 mots sugg\u00e9r\u00e9s",
  "Achievements": "Succ\u00e8s",
  "Achievements & Streaks": "Succ\u00e8s et s\u00e9ries",
  "achievements unlocked": "succ\u00e8s d\u00e9bloqu\u00e9s",
  "Activates all PRO features for 7 days": "Active toutes les fonctionnalit\u00e9s PRO pendant 7 jours",
  "Active days": "Jours actifs",
  "Add": "Ajouter",
  "Add a couple of words \u2014 and we'll begin the journey.": "Ajoutez quelques mots \u2014 et nous commencerons l\u2019aventure.",
  "Add a couple of words and I'll keep them safe here. Little by little \u2014 you'll see your vocabulary grow every day.": "Ajoutez quelques mots et je les garderai en s\u00e9curit\u00e9. Petit \u00e0 petit \u2014 vous verrez votre vocabulaire grandir chaque jour.",
  "Add a memory hint": "Ajouter un indice m\u00e9moire",
  "Add a word": "Ajouter un mot",
  "Add a word you liked": "Ajoutez un mot qui vous a plu",
  "Add all": "Tout ajouter",
  "Add anyway": "Ajouter quand m\u00eame",
  "Add at least 4 words with translations to start practicing.": "Ajoutez au moins 4 mots avec traductions pour commencer \u00e0 pratiquer.",
  "Add at least 4 words with translations to start practicing. Every word counts!": "Ajoutez au moins 4 mots avec traductions pour commencer. Chaque mot compte !",
  "Add translation if you know it": "Ajoutez la traduction si vous la connaissez",
  "Add word": "Ajouter un mot",
  "Add Words": "Ajouter des mots",
  "Add words to receive vocabulary notifications": "Ajoutez des mots pour recevoir des notifications de vocabulaire",
  "Add words with this tag and they'll appear here.": "Ajoutez des mots avec ce tag et ils appara\u00eetront ici.",
  "Add your first word": "Ajoutez votre premier mot",
  "Adding word": "Ajout du mot",
  "Adding...": "Ajout en cours...",
  "Adds the word to your dictionary": "Ajoute le mot \u00e0 votre dictionnaire",
  "AI Translation": "Traduction IA",
  "AI translations": "Traductions IA",
  "AI-powered translations with examples, transcription and context.": "Traductions IA avec exemples, transcription et contexte.",
  "All caught up!": "Tout est \u00e0 jour !",
  "All challenges completed!": "Tous les d\u00e9fis accomplis !",
  "All done!": "Termin\u00e9 !",
  "All effects": "Tous les effets",
  "All themes": "Tous les th\u00e8mes",
  "All words already in your dictionary": "Tous les mots sont d\u00e9j\u00e0 dans votre dictionnaire",
  "All your data \u2014 words, progress, settings and preferences \u2014 is stored locally on your device. Droword does not collect, transmit or store any personal data on external servers.": "Toutes vos donn\u00e9es \u2014 mots, progr\u00e8s, param\u00e8tres et pr\u00e9f\u00e9rences \u2014 sont stock\u00e9es localement sur votre appareil. Droword ne collecte, ne transmet et ne stocke aucune donn\u00e9e personnelle sur des serveurs externes.",
  "Almost!": "Presque !",
  "Already know": "D\u00e9j\u00e0 connu",
  "Animate": "Animer",
  "Anime": "Anim\u00e9",
  "App Language": "Langue de l\u2019appli",
  "App Tour": "Visite guid\u00e9e",
  "Appearance": "Apparence",
  "Apple glass aesthetic": "Esth\u00e9tique Apple Glass",
  "Avg ease": "Facilit\u00e9 moy.",
  "Avg/day": "Moy./jour",
  "Awesome, you've hit your word goal for today.": "Bravo, vous avez atteint votre objectif de mots pour aujourd\u2019hui.",
  "Based on the last 14 days": "Bas\u00e9 sur les 14 derniers jours",
  "Basics": "Les bases",
  "Beginner \ud83d\udc23": "D\u00e9butant \ud83d\udc23",
  "Best day": "Meilleur jour",
  "Best known": "Les mieux connus",
  "Best streak": "Meilleure s\u00e9rie",
  "Build the sentence": "Construisez la phrase",
  "Build your dictionary": "Construisez votre dictionnaire",
  "Bullseye": "Dans le mille",
  "Buying and paying": "Achats et paiements",
  "By tags": "Par tags",
  "calm, confident": "calme, assur\u00e9",
  "Cancel": "Annuler",
  "Centurion": "Centurion",
  "Change photo": "Changer la photo",
  "Change the look anytime": "Changez l\u2019apparence quand vous voulez",
  "Check": "V\u00e9rifier",
  "Choose from gallery": "Choisir dans la galerie",
  "Choose from library": "Choisir dans la biblioth\u00e8que",
  "Choose from multiple themes, seasonal effects and appearance settings.": "Choisissez parmi plusieurs th\u00e8mes, effets saisonniers et param\u00e8tres d\u2019apparence.",
  "Choose languages, voices and themes. Make it yours!": "Choisissez langues, voix et th\u00e8mes. Personnalisez-le !",
  "Choose the correct translation": "Choisissez la bonne traduction",
  "Choose the correct word": "Choisissez le bon mot",
  "Clear search": "Effacer la recherche",
  "Close": "Fermer",
  "Close settings": "Fermer les param\u00e8tres",
  "Color": "Couleur",
  "Consistency is key. Open up and review!": "La r\u00e9gularit\u00e9 est la cl\u00e9. Ouvrez et r\u00e9visez !",
  "Contact": "Contact",
  "Continue": "Continuer",
  "Copy all": "Tout copier",
  "Correct": "Correct",
  "Correct: %@": "Correct : %@",
  "Correct!": "Correct !",
  "Count": "Nombre",
  "Cozy sunset vibes": "Ambiance coucher de soleil",
  "Current season": "Saison actuelle",
  "Daily Challenges": "D\u00e9fis quotidiens",
  "Daily goal reached!": "Objectif quotidien atteint !",
  "Daily goal!": "Objectif quotidien !",
  "Daily Goals": "Objectifs quotidiens",
  "Daily Life": "Vie quotidienne",
  "Daily limit reached": "Limite quotidienne atteinte",
  "Daily motivation": "Motivation quotidienne",
  "Daily reminder": "Rappel quotidien",
  "Daily scan limit reached. Upgrade to Pro for unlimited scans.": "Limite de scans quotidienne atteinte. Passez \u00e0 Pro pour des scans illimit\u00e9s.",
  "Dark": "Sombre",
  "Data Storage": "Stockage des donn\u00e9es",
  "Date": "Date",
  "days remaining": "jours restants",
  "Decorative elements that change with the season \u2014 cherry blossoms in spring, snowflakes in winter, and more.": "\u00c9l\u00e9ments d\u00e9coratifs qui changent avec la saison \u2014 fleurs de cerisier au printemps, flocons en hiver, et plus.",
  "Dedicated Learner": "Apprenant d\u00e9vou\u00e9",
  "Default": "Par d\u00e9faut",
  "Default only": "Par d\u00e9faut uniquement",
  "Delete": "Supprimer",
  "Delete word": "Supprimer le mot",
  "Diamond": "Diamant",
  "Dictionary": "Dictionnaire",
  "Do you remember what this means?": "Vous souvenez-vous de ce que cela signifie ?",
  "Don't know": "Je ne sais pas",
  "Don't know the translation? I'll handle it for you": "Vous ne connaissez pas la traduction ? Je m\u2019en occupe",
  "Don't let your progress fade \u2014 even 2 minutes help.": "Ne laissez pas vos progr\u00e8s s\u2019\u00e9vanouir \u2014 m\u00eame 2 minutes aident.",
  "Done": "Termin\u00e9",
  "Done selecting": "S\u00e9lection termin\u00e9e",
  "Double tap any card to add an emoji reaction. Tap the reaction to change it. A fun way to mark your favourites!": "Appuyez deux fois sur une carte pour ajouter une r\u00e9action emoji. Appuyez sur la r\u00e9action pour la changer. Une fa\u00e7on amusante de marquer vos favoris !",
  "Double tap the card to add a reaction": "Appuyez deux fois sur la carte pour ajouter une r\u00e9action",
  "Droword": "Droword",
  "DROWORD": "DROWORD",
  "Droword PRO": "Droword PRO",
  "Due soon": "Bient\u00f4t \u00e0 r\u00e9viser",
  "Due today": "\u00c0 r\u00e9viser aujourd\u2019hui",
  "e.g. #FFAA33": "ex. #FFAA33",
  "Easy": "Facile",
  "Enable notifications": "Activer les notifications",
  "End time must be after start time": "L\u2019heure de fin doit \u00eatre apr\u00e8s l\u2019heure de d\u00e9but",
  "energetic, expressive": "\u00e9nergique, expressif",
  "Enter a word": "Entrez un mot",
  "Enter tag name": "Entrez le nom du tag",
  "Enter translation": "Entrez la traduction",
  "Enter your name": "Entrez votre nom",
  "Essential everyday words": "Mots essentiels du quotidien",
  "Example": "Exemple",
  "Explorer \ud83e\udd8a": "Explorateur \ud83e\udd8a",
  "Export Words": "Exporter les mots",
  "Extra Large": "Tr\u00e8s grand",
  "Extracting words from photo\u2026": "Extraction des mots de la photo\u2026",
  "Failed to extract words. Please try again.": "\u00c9chec de l\u2019extraction. Veuillez r\u00e9essayer.",
  "Fall": "Automne",
  "Feature Flags": "Options exp\u00e9rimentales",
  "Fill in the blank": "Compl\u00e9tez le blanc",
  "Finding that book was pure serendipity.": "Trouver ce livre \u00e9tait un pur hasard heureux.",
  "Font Size": "Taille de police",
  "Food & Drinks": "Nourriture et boissons",
  "Free": "Gratuit",
  "Fresh green accent": "Accent vert frais",
  "friendly, warm": "amical, chaleureux",
  "From": "D\u00e8s",
  "Fun facts": "Anecdotes",
  "Get Droword PRO": "Obtenir Droword PRO",
  "Get notified when you reach 7, 30, 100 and 365 day streaks.": "Soyez notifi\u00e9 quand vous atteignez 7, 30, 100 et 365 jours cons\u00e9cutifs.",
  "Get Started": "Commencer",
  "Getting around and exploring": "Se d\u00e9placer et explorer",
  "Go to Practice for multiple choice, typing, and fill-in-the-blank quizzes. Choose your preferred direction \u2014 word to translation or vice versa.": "Allez dans Pratique pour des QCM, de la saisie et des exercices \u00e0 trous. Choisissez votre direction pr\u00e9f\u00e9r\u00e9e \u2014 mot vers traduction ou inversement.",
  "Good": "Bien",
  "Got it": "Compris",
  "Got it!": "Compris !",
  "Great job!": "Bravo !",
  "Half a thousand words. That's %lld words per week on average!": "Cinq cents mots. Soit %lld mots par semaine en moyenne !",
  "Hard": "Difficile",
  "Hide examples": "Masquer les exemples",
  "Hint: %@": "Indice : %@",
  "Hint: \u304a..., 2 letters": "Indice : \u304a..., 2 lettres",
  "Home and routine": "Maison et routine",
  "I can translate it for you": "Je peux le traduire pour vous",
  "I speak": "Je parle",
  "I'm learning": "J\u2019apprends",
  "Import Complete": "Importation termin\u00e9e",
  "Import Words": "Importer des mots",
  "Include mastered": "Inclure les ma\u00eetris\u00e9s",
  "Instagram Stories": "Instagram Stories",
  "It's been a while \u2014 your words are waiting!": "Cela fait un moment \u2014 vos mots vous attendent !",
  "Keep going!": "Continuez !",
  "Keep growing!": "Continuez \u00e0 progresser !",
  "Keep practicing!": "Continuez \u00e0 pratiquer !",
  "Known": "Connu",
  "Language Pair": "Paire de langues",
  "Language Preferences": "Pr\u00e9f\u00e9rences linguistiques",
  "Large": "Grand",
  "Last updated: April 2026": "Derni\u00e8re mise \u00e0 jour : avril 2026",
  "Learn vocabulary smarter": "Apprenez le vocabulaire plus intelligemment",
  "Learned something cool?": "Appris quelque chose de cool ?",
  "Learning": "Apprentissage",
  "Least known": "Les moins connus",
  "Legend \ud83c\udf1f": "L\u00e9gende \ud83c\udf1f",
  "Light": "Clair",
  "Linguist \ud83e\udd89": "Linguiste \ud83e\udd89",
  "Link it to something you know": "Associez-le \u00e0 quelque chose que vous connaissez",
  "Listen to words with customizable voice and speech rate.": "\u00c9coutez les mots avec une voix et un d\u00e9bit personnalisables.",
  "Listening Mode": "Mode \u00e9coute",
  "Make it yours": "Personnalisez-le",
  "Manage Subscription": "G\u00e9rer l\u2019abonnement",
  "Marksman": "Tireur d\u2019\u00e9lite",
  "Master \ud83d\udc09": "Ma\u00eetre \ud83d\udc09",
  "Mastery": "Ma\u00eetrise",
  "Match the pairs": "Associez les paires",
  "Memory hint": "Indice m\u00e9moire",
  "Memory Keeper": "Gardien de m\u00e9moire",
  "Minutes": "Minutes",
  "Missed": "Rat\u00e9",
  "Mixed Quizzes": "Quiz mixtes",
  "Monthly": "Mensuel",
  "Monthly Master": "Ma\u00eetre mensuel",
  "Monthly plan, %@": "Abonnement mensuel, %@",
  "More examples": "Plus d\u2019exemples",
  "More languages": "Plus de langues",
  "Movie": "Film",
  "Multiple choice, cloze, matching, typing and sentence building exercises.": "QCM, texte \u00e0 trous, association, saisie et construction de phrases.",
  "Name": "Nom",
  "Name *": "Nom *",
  "Name required": "Nom requis",
  "New": "Nouveau",
  "New Tag": "Nouveau tag",
  "New word": "Nouveau mot",
  "New word to remember": "Nouveau mot \u00e0 retenir",
  "New words won't get translations until tomorrow. Upgrade to Pro for unlimited.": "Les nouveaux mots ne seront pas traduits avant demain. Passez \u00e0 Pro pour un acc\u00e8s illimit\u00e9.",
  "Newest": "Plus r\u00e9cents",
  "Next": "Suivant",
  "Next Review": "Prochaine r\u00e9vision",
  "Next review tomorrow": "Prochaine r\u00e9vision demain",
  "Nice start!": "Bon d\u00e9but !",
  "No activity": "Aucune activit\u00e9",
  "No credit card required": "Pas de carte bancaire requise",
  "No internet connection": "Pas de connexion internet",
  "No tag": "Pas de tag",
  "No words found": "Aucun mot trouv\u00e9",
  "No words found in the image. Try a clearer photo.": "Aucun mot trouv\u00e9 dans l\u2019image. Essayez une photo plus nette.",
  "No words in \u00ab%@\u00bb": "Aucun mot dans \u00ab %@ \u00bb",
  "Not enough words yet": "Pas encore assez de mots",
  "Not sure? Skip for now": "Pas s\u00fbr ? Passez pour l\u2019instant",
  "Notifications": "Notifications",
  "Noun": "Nom",
  "now": "maintenant",
  "of %lld": "sur %lld",
  "OK": "OK",
  "Oldest": "Plus anciens",
  "On fire!": "En feu !",
  "On Target": "Dans la cible",
  "Onboarding": "Accueil",
  "One small step today \u2014 closer to your goal.": "Un petit pas aujourd\u2019hui \u2014 plus pr\u00e8s de votre objectif.",
  "Oops! Something went wrong.": "Oups ! Quelque chose s\u2019est mal pass\u00e9.",
  "Open Mind": "Esprit ouvert",
  "Opens settings": "Ouvre les param\u00e8tres",
  "or subscribe": "ou abonnez-vous",
  "Organizer": "Organisateur",
  "Other": "Autre",
  "Outstanding!": "Exceptionnel !",
  "Parts of speech": "Classes grammaticales",
  "Payment will be charged to your Apple ID account at confirmation of purchase. Subscription automatically renews unless it is canceled at least 24 hours before the end of the current period. Your account will be charged for renewal within 24 hours prior to the end of the current period. You can manage and cancel your subscriptions in your App Store account settings.": "Le paiement sera factur\u00e9 \u00e0 votre compte Apple ID lors de la confirmation d\u2019achat. L\u2019abonnement se renouvelle automatiquement sauf annulation au moins 24 heures avant la fin de la p\u00e9riode en cours. Votre compte sera d\u00e9bit\u00e9 pour le renouvellement dans les 24 heures pr\u00e9c\u00e9dant la fin de la p\u00e9riode. Vous pouvez g\u00e9rer et annuler vos abonnements dans les r\u00e9glages de votre compte App Store.",
  "Per day": "Par jour",
  "per month": "par mois",
  "Perfect 10!": "10 sur 10 !",
  "Perfect Score": "Score parfait",
  "Personal details": "Informations personnelles",
  "Plan": "Forfait",
  "Play pronunciation": "Lire la prononciation",
  "Plays audio for %@": "Lit l\u2019audio pour %@",
  "Practice": "Pratique",
  "Practice Quizzes": "Quiz de pratique",
  "Preview voice %@": "Aper\u00e7u de la voix %@",
  "Price": "Prix",
  "Privacy Policy": "Politique de confidentialit\u00e9",
  "PRO": "PRO",
  "PRO Active": "PRO actif",
  "PRO is active": "PRO est actif",
  "PRO Trial": "Essai PRO",
  "Processing": "Traitement en cours",
  "Product not available. Check your connection.": "Produit non disponible. V\u00e9rifiez votre connexion.",
  "Profile photo": "Photo de profil",
  "Put on headphones and learn while doing other things. Audio flashcards with customizable pauses and speed.": "Mettez vos \u00e9couteurs et apprenez en faisant autre chose. Cartes audio avec pauses et vitesse personnalisables.",
  "Quiz Legend": "L\u00e9gende du quiz",
  "Quiz Machine": "Machine \u00e0 quiz",
  "Quiz Pro": "Quiz Pro",
  "Quiz Rookie": "D\u00e9butant en quiz",
  "Quizzes": "Quiz",
  "React to Words": "R\u00e9agir aux mots",
  "Recently added": "Ajout\u00e9s r\u00e9cemment",
  "Reminder time": "Heure du rappel",
  "Remove photo": "Supprimer la photo",
  "Renews": "Renouvellement",
  "Request timed out. Please try again.": "D\u00e9lai d\u00e9pass\u00e9. Veuillez r\u00e9essayer.",
  "Restore purchases": "Restaurer les achats",
  "Review": "R\u00e9vision",
  "Review card: %@": "Carte de r\u00e9vision : %@",
  "Review Cards": "Cartes de r\u00e9vision",
  "Review with a spaced schedule to keep words fresh in memory.": "R\u00e9visez \u00e0 intervalles espac\u00e9s pour garder les mots frais en m\u00e9moire.",
  "Review words at optimal intervals so they stick in long-term memory.": "R\u00e9visez les mots \u00e0 intervalles optimaux pour les ancrer dans la m\u00e9moire \u00e0 long terme.",
  "Royalty": "Royaut\u00e9",
  "Sapling": "Jeune pousse",
  "Save": "Enregistrer",
  "Save 25%": "\u00c9conomisez 25%",
  "Save words with examples, tags and notes so they stay with you.": "Enregistrez les mots avec exemples, tags et notes pour les garder avec vous.",
  "Saved offline \u2014 will update when connected": "Enregistr\u00e9 hors ligne \u2014 mis \u00e0 jour une fois connect\u00e9",
  "Saved.": "Enregistr\u00e9.",
  "Scan another photo": "Scanner une autre photo",
  "Scan words": "Scanner des mots",
  "Scan words from photo": "Scanner les mots depuis une photo",
  "Search words, translations, examples...": "Rechercher mots, traductions, exemples...",
  "Seasonal effects": "Effets saisonniers",
  "See Apple Settings": "Voir les r\u00e9glages Apple",
  "Seedling": "Plantule",
  "Select": "S\u00e9lectionner",
  "Select all (%lld)": "Tout s\u00e9lectionner (%lld)",
  "Select words": "S\u00e9lectionner les mots",
  "Serendipity": "S\u00e9rendipit\u00e9",
  "Share": "Partager",
  "Share word": "Partager le mot",
  "Sharpshooter": "Tireur d\u2019\u00e9lite",
  "Shopping": "Shopping",
  "Show answer": "Afficher la r\u00e9ponse",
  "Show effects": "Afficher les effets",
  "Show transcription": "Afficher la transcription",
  "Show translation": "Afficher la traduction",
  "Skip": "Passer",
  "Skip tour": "Passer la visite",
  "Small": "Petit",
  "Small steps, big vocabulary. Let's go!": "Petits pas, grand vocabulaire. C\u2019est parti !",
  "Smart Dictionary": "Dictionnaire intelligent",
  "Smart practice": "Pratique intelligente",
  "Smart Repetition": "R\u00e9p\u00e9tition intelligente",
  "Smart suggestions just for you": "Suggestions intelligentes rien que pour vous",
  "Social media": "R\u00e9seaux sociaux",
  "soft, neutral": "doux, neutre",
  "Something went wrong. Try again.": "Quelque chose s\u2019est mal pass\u00e9. R\u00e9essayez.",
  "Something you heard today?": "Quelque chose entendu aujourd\u2019hui ?",
  "Spaced Repetition": "R\u00e9p\u00e9tition espac\u00e9e",
  "Speed": "Vitesse",
  "Spring": "Printemps",
  "Sprout": "Pousse",
  "Start 7-day free trial": "D\u00e9marrer l\u2019essai gratuit de 7 jours",
  "Start 7-Day Free Trial": "D\u00e9marrer l\u2019essai gratuit de 7 jours",
  "Start learning to see your time chart": "Commencez \u00e0 apprendre pour voir votre graphique",
  "Start with these words": "Commencez avec ces mots",
  "Stats": "Statistiques",
  "Stats: %lld total, %lld today": "Stats : %lld au total, %lld aujourd\u2019hui",
  "Stay curious": "Restez curieux",
  "Streak": "S\u00e9rie",
  "Streak freeze": "Gel de s\u00e9rie",
  "Streak milestone!": "Jalon de s\u00e9rie !",
  "Streak milestones": "Jalons de s\u00e9rie",
  "Streaks": "S\u00e9ries",
  "Street": "Rue",
  "Study time": "Temps d\u2019\u00e9tude",
  "Subscribe": "S\u2019abonner",
  "Subscribe to Droword PRO": "S\u2019abonner \u00e0 Droword PRO",
  "Subscription renews automatically. You can cancel anytime in Settings \u2192 Apple ID \u2192 Subscriptions.": "L\u2019abonnement se renouvelle automatiquement. Annulez \u00e0 tout moment dans R\u00e9glages \u2192 Apple ID \u2192 Abonnements.",
  "Suggested": "Sugg\u00e9r\u00e9s",
  "Suggested Words": "Mots sugg\u00e9r\u00e9s",
  "Suggestions": "Suggestions",
  "Summer": "\u00c9t\u00e9",
  "Switch": "Changer",
  "Switch to %@?": "Passer \u00e0 %@ ?",
  "System": "Syst\u00e8me",
  "Take a photo": "Prendre une photo",
  "Take a photo of a word list, textbook page, or handout": "Prenez en photo une liste de mots, une page de manuel ou un document",
  "Tap any word to add it to your dictionary": "Appuyez sur un mot pour l\u2019ajouter \u00e0 votre dictionnaire",
  "Tap for detailed statistics": "Appuyez pour voir les statistiques d\u00e9taill\u00e9es",
  "Tap the + tab to add new words. I'll translate them, find examples, and create flashcards automatically.": "Appuyez sur + pour ajouter des mots. Je les traduis, trouve des exemples et cr\u00e9e des cartes automatiquement.",
  "Tap to change your photo": "Appuyez pour changer votre photo",
  "Tap to upgrade to Pro": "Appuyez pour passer \u00e0 Pro",
  "Tap words to build the sentence": "Appuyez sur les mots pour construire la phrase",
  "Tap your stats to see detailed charts, streaks, and achievements. Every word counts toward your goals.": "Appuyez sur vos stats pour voir graphiques, s\u00e9ries et succ\u00e8s. Chaque mot compte pour vos objectifs.",
  "tea": "th\u00e9",
  "Terms of Use": "Conditions d\u2019utilisation",
  "Text-to-Speech": "Synth\u00e8se vocale",
  "That's all it takes to start learning.": "C\u2019est tout ce qu\u2019il faut pour commencer.",
  "That's an impressive collection.": "C\u2019est une collection impressionnante.",
  "The app uses spaced repetition \u2014 you review words right before you'd forget them. Easy words come back less often, hard words more.": "L\u2019appli utilise la r\u00e9p\u00e9tition espac\u00e9e \u2014 vous r\u00e9visez les mots juste avant de les oublier. Les mots faciles reviennent moins souvent, les difficiles plus.",
  "The request took too long. Please try again.": "La requ\u00eate a pris trop de temps. Veuillez r\u00e9essayer.",
  "The word will be saved and enriched with translation and examples once you're back online.": "Le mot sera sauvegard\u00e9 et enrichi avec la traduction et des exemples une fois reconnect\u00e9.",
  "Theme": "Th\u00e8me",
  "Themed vocabulary sets \u2014 basics, food, travel and more.": "Ensembles de vocabulaire th\u00e9matiques \u2014 bases, nourriture, voyage et plus.",
  "Themes": "Th\u00e8mes",
  "Themes & Customization": "Th\u00e8mes et personnalisation",
  "This action cannot be undone.": "Cette action est irr\u00e9versible.",
  "This week": "Cette semaine",
  "Time": "Temps",
  "Time to learn!": "C\u2019est l\u2019heure d\u2019apprendre !",
  "Tip: grab words from movies, chats, or walks \u2014 learning feels alive that way.": "Astuce : notez des mots vus dans des films, des chats ou en promenade \u2014 l\u2019apprentissage prend vie.",
  "Today": "Aujourd\u2019hui",
  "Total": "Total",
  "Total completed: %lld": "Total termin\u00e9 : %lld",
  "Total lapses": "Total des oublis",
  "Total study time: %@": "Temps d\u2019\u00e9tude total : %@",
  "Track Your Progress": "Suivez vos progr\u00e8s",
  "Track your progress with badges, daily challenges and streak calendar.": "Suivez vos progr\u00e8s avec des badges, d\u00e9fis quotidiens et calendrier de s\u00e9ries.",
  "Translation": "Traduction",
  "Travel": "Voyage",
  "Trial: %lld days remaining": "Essai : %lld jours restants",
  "Try a different search or remove the filter.": "Essayez une autre recherche ou retirez le filtre.",
  "Try Again": "R\u00e9essayer",
  "Try Pro free for 7 days": "Essayez Pro gratuitement pendant 7 jours",
  "Type the missing word": "Tapez le mot manquant",
  "Type the translation": "Tapez la traduction",
  "Type the word": "Tapez le mot",
  "Unlimited": "Illimit\u00e9",
  "Unlimited access": "Acc\u00e8s illimit\u00e9",
  "Unlimited access to all features": "Acc\u00e8s illimit\u00e9 \u00e0 toutes les fonctionnalit\u00e9s",
  "Unlock unlimited AI features": "D\u00e9bloquer les fonctionnalit\u00e9s IA illimit\u00e9es",
  "Unlock unlimited reviews": "D\u00e9bloquer les r\u00e9visions illimit\u00e9es",
  "Unstoppable": "Inarr\u00eatable",
  "Unstoppable!": "Inarr\u00eatable !",
  "Until": "Jusqu\u2019\u00e0",
  "Upgrade": "Mettre \u00e0 niveau",
  "Version %@": "Version %@",
  "Vocab Builder": "Constructeur de vocabulaire",
  "Vocabulary": "Vocabulaire",
  "Voice": "Voix",
  "Voice & Pronunciation": "Voix et prononciation",
  "Voice & Speech": "Voix et parole",
  "Voice pronunciation": "Prononciation vocale",
  "Warm and vibrant": "Chaleureux et vibrant",
  "We miss you!": "Vous nous manquez !",
  "Week Warrior": "Guerrier de la semaine",
  "What does it remind you of?": "\u00c0 quoi cela vous fait-il penser ?",
  "What to eat and drink": "Que manger et boire",
  "What's New": "Nouveaut\u00e9s",
  "When you add or translate a word, the text is sent to a third-party AI service (Anthropic Claude) to generate translations, explanations and examples. No personal information is included in these requests.": "Quand vous ajoutez ou traduisez un mot, le texte est envoy\u00e9 \u00e0 un service IA tiers (Anthropic Claude) pour g\u00e9n\u00e9rer traductions, explications et exemples. Aucune information personnelle n\u2019est incluse.",
  "Where did you hear it?": "O\u00f9 l\u2019avez-vous entendu ?",
  "Winter": "Hiver",
  "Word already exists": "Le mot existe d\u00e9j\u00e0",
  "Word Collector": "Collectionneur de mots",
  "Word Explorer": "Explorateur de mots",
  "Word notifications": "Notifications de mots",
  "Word of the day": "Mot du jour",
  "Word or phrase *": "Mot ou expression *",
  "Word Packs": "Packs de mots",
  "Word suggestions": "Suggestions de mots",
  "Words": "Mots",
  "Words appear on the home screen when it's time to review. Swipe through them to keep your memory fresh.": "Les mots apparaissent sur l\u2019\u00e9cran d\u2019accueil quand c\u2019est l\u2019heure de r\u00e9viser. Faites d\u00e9filer pour garder votre m\u00e9moire fra\u00eeche.",
  "Words to review": "Mots \u00e0 r\u00e9viser",
  "Works with exports from Anki, Quizlet, and any CSV or TXT file. Minimum: a column named \"Word\". Translations will be added automatically if missing.": "Compatible avec les exports d\u2019Anki, Quizlet et tout fichier CSV ou TXT. Minimum : une colonne nomm\u00e9e \u00ab Word \u00bb. Les traductions seront ajout\u00e9es automatiquement si absentes.",
  "Write the meaning here": "\u00c9crivez la signification ici",
  "x%lld streak!": "S\u00e9rie de %lld jours !",
  "Yearly": "Annuel",
  "Yearly plan, %@": "Abonnement annuel, %@",
  "You can delete all your data at any time from Settings \u2192 Dictionary \u2192 Clear All Words. Removing the app from your device deletes all stored data permanently.": "Vous pouvez supprimer toutes vos donn\u00e9es \u00e0 tout moment depuis R\u00e9glages \u2192 Dictionnaire \u2192 Effacer tous les mots. Supprimer l\u2019appli de votre appareil efface toutes les donn\u00e9es d\u00e9finitivement.",
  "You have full access": "Vous avez un acc\u00e8s complet",
  "You're learning %lld words a week \u2014 great pace!": "Vous apprenez %lld mots par semaine \u2014 bon rythme !",
  "You're learning about %lld words a week. Keep it up!": "Vous apprenez environ %lld mots par semaine. Continuez !",
  "You're off to a great start.": "Vous \u00eates bien parti.",
  "You've hit your target for today. Total: %lld words.": "Vous avez atteint votre objectif du jour. Total : %lld mots.",
  "Your answer": "Votre r\u00e9ponse",
  "Your daily word moment": "Votre moment vocabulaire quotidien",
  "Your recent words will appear here.": "Vos mots r\u00e9cents appara\u00eetront ici.",
  "Your vocabulary misses you. Let's pick up where you left off!": "Votre vocabulaire vous attend. Reprenons o\u00f9 vous en \u00e9tiez !",
  "Your word garden is waiting": "Votre jardin de mots vous attend",
  "Your word of the day": "Votre mot du jour",
  "Your words are waiting. A quick session?": "Vos mots vous attendent. Une petite session ?",
  "Z \u2192 A": "Z \u2192 A",
  "\u0421\u0447\u0430\u0441\u0442\u043b\u0438\u0432\u0430\u044f \u0441\u043b\u0443\u0447\u0430\u0439\u043d\u043e\u0441\u0442\u044c": "Heureux hasard",
  "\u304a\u8336": "th\u00e9",
  "\u8336": "th\u00e9",
  // Plural keys - French uses "one" and "other"
  "%@..., %lld letters": { one: "%@\u2026, %lld lettre", other: "%@\u2026, %lld lettres" },
  "%lld days": { one: "%lld jour", other: "%lld jours" },
  "%lld days remaining": { one: "%lld jour restant", other: "%lld jours restants" },
  "%lld months": { one: "%lld mois", other: "%lld mois" },
  "%lld words": { one: "%lld mot", other: "%lld mots" },
  "%lld words added to your dictionary": { one: "%lld mot ajout\u00e9 \u00e0 votre dictionnaire", other: "%lld mots ajout\u00e9s \u00e0 votre dictionnaire" },
  "%lld words found": { one: "%lld mot trouv\u00e9", other: "%lld mots trouv\u00e9s" },
  "%lld words imported successfully.": { one: "%lld mot import\u00e9 avec succ\u00e8s.", other: "%lld mots import\u00e9s avec succ\u00e8s." },
  "%lld words to review": { one: "%lld mot \u00e0 r\u00e9viser", other: "%lld mots \u00e0 r\u00e9viser" },
  "%lld words to review in %@": { one: "%1$lld mot \u00e0 r\u00e9viser dans %2$@", other: "%1$lld mots \u00e0 r\u00e9viser dans %2$@" },
  "%lld words updated with translations": { one: "%lld mot mis \u00e0 jour avec traduction", other: "%lld mots mis \u00e0 jour avec traductions" },
  "%lld words!": { one: "%lld mot !", other: "%lld mots !" },
  "%lld years": { one: "%lld an", other: "%lld ans" },
  "Add %lld new words": { one: "Ajouter %lld nouveau mot", other: "Ajouter %lld nouveaux mots" },
  "Add %lld tagged words": { one: "Ajouter %lld mot tagg\u00e9", other: "Ajouter %lld mots tagg\u00e9s" },
  "Best day: %@ (%lld words)": { one: "Meilleur jour : %@ (%lld mot)", other: "Meilleur jour : %@ (%lld mots)" },
  "Clear %lld words": { one: "Effacer %lld mot", other: "Effacer %lld mots" },
  "Complete %lld quizzes": { one: "Compl\u00e9ter %lld quiz", other: "Compl\u00e9ter %lld quiz" },
  "Delete %lld words": { one: "Supprimer %lld mot", other: "Supprimer %lld mots" },
  "Delete %lld words?": { one: "Supprimer %lld mot ?", other: "Supprimer %lld mots ?" },
  "Learning for %lld days": { one: "Apprentissage depuis %lld jour", other: "Apprentissage depuis %lld jours" },
  "Next review in %lld days": { one: "Prochaine r\u00e9vision dans %lld jour", other: "Prochaine r\u00e9vision dans %lld jours" },
  "Review %lld due words": { one: "R\u00e9viser %lld mot en attente", other: "R\u00e9viser %lld mots en attente" },
  "Study for %lld minutes": { one: "\u00c9tudier pendant %lld minute", other: "\u00c9tudier pendant %lld minutes" },
  "You have %lld words in %@. They will stay in your dictionary.": { one: "Vous avez %1$lld mot en %2$@. Il restera dans votre dictionnaire.", other: "Vous avez %1$lld mots en %2$@. Ils resteront dans votre dictionnaire." },
  "You reviewed %lld words.\nNew reviews will appear when it's time to practice.": { one: "Vous avez r\u00e9vis\u00e9 %lld mot.\nDe nouvelles r\u00e9visions appara\u00eetront quand il sera temps de pratiquer.", other: "Vous avez r\u00e9vis\u00e9 %lld mots.\nDe nouvelles r\u00e9visions appara\u00eetront quand il sera temps de pratiquer." },
  "You've been learning for %lld days in a row. Keep going!": { one: "Vous apprenez depuis %lld jour cons\u00e9cutif. Continuez !", other: "Vous apprenez depuis %lld jours cons\u00e9cutifs. Continuez !" },
  // Non-plural achievement keys
  "Add 10 words": "Ajouter 10 mots",
  "Add 25 words": "Ajouter 25 mots",
  "Add 50 words": "Ajouter 50 mots",
  "Add 100 words": "Ajouter 100 mots",
  "Add 200 words": "Ajouter 200 mots",
  "Add 500 words": "Ajouter 500 mots",
  "Complete 5 daily goals": "Compl\u00e9ter 5 objectifs quotidiens",
  "Complete 10 daily goals": "Compl\u00e9ter 10 objectifs quotidiens",
  "Complete 10 quizzes": "Compl\u00e9ter 10 quiz",
  "Complete 25 daily goals": "Compl\u00e9ter 25 objectifs quotidiens",
  "Complete 50 daily goals": "Compl\u00e9ter 50 objectifs quotidiens",
  "Complete 50 quizzes": "Compl\u00e9ter 50 quiz",
  "Complete 100 quizzes": "Compl\u00e9ter 100 quiz",
  "Complete a quiz with 100%": "Compl\u00e9ter un quiz \u00e0 100%",
};

// Curly quote variants
translations["Don\u2019t know the translation? I\u2019ll handle it for you"] = "Vous ne connaissez pas la traduction ? Je m\u2019en occupe";
translations["I\u2019m learning"] = "J\u2019apprends";

// Process all keys
let addedCount = 0;
let skippedCount = 0;
let pluralCount = 0;

for (const [key, entry] of Object.entries(data.strings)) {
  // Skip if already has French
  if (entry.localizations?.fr) {
    skippedCount++;
    continue;
  }

  const translation = translations[key];
  if (translation === undefined) continue;

  if (!entry.localizations) entry.localizations = {};

  if (typeof translation === 'object' && translation.one !== undefined) {
    // Plural form
    entry.localizations.fr = {
      variations: {
        plural: {
          one: {
            stringUnit: {
              state: "translated",
              value: translation.one
            }
          },
          other: {
            stringUnit: {
              state: "translated",
              value: translation.other
            }
          }
        }
      }
    };
    pluralCount++;
    addedCount++;
  } else {
    // Check if this key has plural in other languages
    const isPlural = JSON.stringify(entry).includes('"plural"');
    if (isPlural && typeof translation === 'string') {
      // Plural key but we only have one form — use "other" only like Japanese
      entry.localizations.fr = {
        variations: {
          plural: {
            one: {
              stringUnit: {
                state: "translated",
                value: translation
              }
            },
            other: {
              stringUnit: {
                state: "translated",
                value: translation
              }
            }
          }
        }
      };
      pluralCount++;
    } else {
      entry.localizations.fr = {
        stringUnit: {
          state: "translated",
          value: translation
        }
      };
    }
    addedCount++;
  }
}

// Handle %lld/%lld challenges done specially (has substitution pattern)
const challKey = '%lld/%lld challenges done';
if (data.strings[challKey] && !data.strings[challKey].localizations?.fr) {
  data.strings[challKey].localizations = data.strings[challKey].localizations || {};
  data.strings[challKey].localizations.fr = {
    stringUnit: {
      state: "translated",
      value: "%1$lld/%2$lld d\u00e9fis accomplis"
    }
  };
  addedCount++;
}

fs.writeFileSync(filePath, JSON.stringify(data, null, 2) + '\n');
console.log(`Added: ${addedCount}, Skipped (already had fr): ${skippedCount}, Plural: ${pluralCount}`);

// Check for keys without French
let missing = 0;
const missingKeys = [];
for (const [key, entry] of Object.entries(data.strings)) {
  if (!entry.localizations?.fr) {
    missing++;
    missingKeys.push(key);
  }
}
console.log(`Missing French: ${missing}`);
if (missingKeys.length > 0) {
  console.log('Missing keys:', JSON.stringify(missingKeys));
}
