import Foundation

enum AppStorageKeys {
    static let isPremium = "isPremium"
    static let userName = "userName"
    static let appAppearance = "appAppearance"
    static let currentStreak = "currentStreak"
    static let hasCompletedOnboarding = "hasCompletedOnboarding"
    static let hasUsedTrial = "hasUsedTrial"
    static let trialStartDate = "trialStartDate"
    static let firstUseDate = "firstUseDate"
    static let lastActiveDay = "lastActiveDay"
    static let daysUsedCount = "daysUsedCount"
    static let selectedCuteTag = "selectedCuteTag"
    static let selectedCuteTagDate = "selectedCuteTagDate"
    static let hasSeenReviewPaywall = "hasSeenReviewPaywall"
    static let hasSeenOfflineAlert = "hasSeenOfflineAlert"
    static let notifDailyReminders = "notifDailyReminders"
    static let notifStreakMilestones = "notifStreakMilestones"
    static let ttsVoice = "ttsVoice"
    static let ttsRate = "ttsRate"
    static let seasonalEffectsEnabled = "seasonalEffectsEnabled"
    static let seasonalAnimationEnabled = "seasonalAnimationEnabled"
    static let hasSeenGoldenIntro = "hasSeenGoldenIntro"
    static let hasSeenCoachMarks = "hasSeenCoachMarks"
    static let lastCelebratedWordCount = "lastCelebratedWordCount"
    static let lastCelebratedDailyGoal = "lastCelebratedDailyGoal"
    static let debugPremiumOverride = "debugPremiumOverride"
}
