import Foundation

enum AppStorageKeys {
    static let isPremium = "isPremium"
    static let userName = "userName"
    static let appAppearance = "appAppearance"
    static let currentStreak = "currentStreak"
    static let hasCompletedOnboarding = "hasCompletedOnboarding"
    static let hasUsedTrial = "hasUsedTrial"
    static let trialStartDate = "trialStartDate"
    static let firstUseDate = "firstUseDate"
    static let lastActiveDay = "lastActiveDay"
    static let daysUsedCount = "daysUsedCount"
    static let selectedCuteTag = "selectedCuteTag"
    static let selectedCuteTagDate = "selectedCuteTagDate"
    static let hasSeenReviewPaywall = "hasSeenReviewPaywall"
    static let hasSeenOfflineAlert = "hasSeenOfflineAlert"
    static let notifDailyReminders = "notifDailyReminders"
    static let notifStreakMilestones = "notifStreakMilestones"

    static let notifGlobalEnabled = "notifGlobalEnabled"
    static let notifDailyReminderEnabled = "notifDailyReminderEnabled"
    static let notifDailyReminderHour = "notifDailyReminderHour"
    static let notifDailyReminderMinute = "notifDailyReminderMinute"
    static let notifVocabEnabled = "notifVocabEnabled"
    static let notifVocabShowTranscription = "notifVocabShowTranscription"
    static let notifVocabShowTranslation = "notifVocabShowTranslation"
    static let notifVocabIncludeMastered = "notifVocabIncludeMastered"
    static let notifVocabFrequency = "notifVocabFrequency"
    static let notifVocabStartHour = "notifVocabStartHour"
    static let notifVocabStartMinute = "notifVocabStartMinute"
    static let notifVocabEndHour = "notifVocabEndHour"
    static let notifVocabEndMinute = "notifVocabEndMinute"
    static let ttsVoice = "ttsVoice"
    static let ttsRate = "ttsRate"
    static let seasonalEffectsEnabled = "seasonalEffectsEnabled"
    static let seasonalAnimationEnabled = "seasonalAnimationEnabled"
    static let hasSeenSuggestedIntro = "hasSeenSuggestedIntro"
    static let hasSeenCoachMarks = "hasSeenCoachMarks"
    static let lastCelebratedWordCount = "lastCelebratedWordCount"
    static let lastCelebratedDailyGoal = "lastCelebratedDailyGoal"
    static let debugPremiumOverride = "debugPremiumOverride"
    static let hasEverAddedWord = "hasEverAddedWord"
    static let reviewAllCaughtUp = "reviewAllCaughtUp"
    static let reviewDismissed = "reviewDismissed"
    static let reviewSessionDate = "reviewSessionDate"
    static let fontScale = "fontScale"
    static let hasSeenFirstWords = "hasSeenFirstWords"
    static let hasSeenStreakPaywall = "hasSeenStreakPaywall"
    static let hasSeenPerfectQuizPaywall = "hasSeenPerfectQuizPaywall"
    static let lastCelebratedStreak = "lastCelebratedStreak"
    static let lastStreakFreezeDate = "lastStreakFreezeDate"
    static let hasSeenReactionHint = "hasSeenReactionHint"
}
