import Foundation

enum NotificationCopy {

    private static var languageCode: String {
        let preferred = Locale.preferredLanguages.first ?? Locale.current.identifier
        let id = preferred.replacingOccurrences(of: "_", with: "-")
        let lower = id.lowercased()
        if lower.hasPrefix("zh-hant") || lower.hasPrefix("zh-tw") || lower.hasPrefix("zh-hk") || lower.hasPrefix("zh-mo") {
            return "zh-Hant"
        }
        if lower.hasPrefix("zh") {
            return "zh-Hans"
        }
        if lower.hasPrefix("pt") {
            return "pt-PT"
        }
        return String(id.prefix(2))
    }

    private static func t(_ table: [String: String]) -> String {
        let code = languageCode
        if let exact = table[code] { return exact }
        let short = String(code.prefix(2))
        return table[short] ?? table["en"] ?? ""
    }

    private static var dayIndex: Int {
        Calendar.current.ordinality(of: .day, in: .year, for: Date()) ?? 0
    }

    private static func L(
        _ en: String, ru: String, de: String, es: String, fr: String,
        ja: String, ko: String, ar: String, it: String,
        zhHans: String, zhHant: String, pt: String
    ) -> [String: String] {
        [
            "en": en, "ru": ru, "de": de, "es": es, "fr": fr,
            "ja": ja, "ko": ko, "ar": ar, "it": it,
            "zh-Hans": zhHans, "zh-Hant": zhHant, "pt-PT": pt
        ]
    }

    private static func pick(_ pairs: [([String: String], [String: String])]) -> (title: String, body: String) {
        let i = dayIndex % max(pairs.count, 1)
        return (t(pairs[i].0), t(pairs[i].1))
    }



    static func pickDaily() -> (title: String, body: String) {
        pick([
            (
                L("bestie open the app",
                  ru: "бести открой апп",
                  de: "bestie öffne die app",
                  es: "bestie abre la app",
                  fr: "bestie ouvre l’app",
                  ja: "ベスティー、アプリ開けて",
                  ko: "베스티 앱 열어",
                  ar: "بستّي افتح الأب",
                  it: "bestie apri l’app",
                  zhHans: "bestie 打开 app",
                  zhHant: "bestie 打開 app",
                  pt: "bestie abre a app"),
                L("your streak is shaking rn. two minutes. do it.",
                  ru: "серия трясётся. две минуты. сделай.",
                  de: "deine serie zittert rn. zwei minuten. mach’s.",
                  es: "tu racha está temblando rn. dos minutos. hazlo.",
                  fr: "ta série tremble rn. deux minutes. fais-le.",
                  ja: "連続が今揺れてる。2分。やって。",
                  ko: "연속이 지금 흔들림. 2분. 해.",
                  ar: "سلسلتك عم ترجف هلأ. دقيقتين. سوّيها.",
                  it: "la serie trema rn. due minuti. falla.",
                  zhHans: "连续打卡在抖。两分钟。去做。",
                  zhHant: "連續打卡在抖。兩分鐘。去做。",
                  pt: "a sequência está a tremer rn. dois minutos. faz.")
            ),
            (
                L("plot twist: you study today",
                  ru: "плот твист: сегодня ты учишь",
                  de: "plot twist: du lernst heute",
                  es: "plot twist: estudias hoy",
                  fr: "plot twist: tu étudies aujourd’hui",
                  ja: "どんでん返し：今日勉強する",
                  ko: "반전: 오늘 공부함",
                  ar: "تويست: اليوم بتدرس",
                  it: "plot twist: studi oggi",
                  zhHans: "剧情反转：你今天学",
                  zhHant: "劇情反轉：你今天學",
                  pt: "plot twist: estudas hoje"),
                L("scrolling ≠ studying. open droword. soft threat.",
                  ru: "скролл ≠ учёба. открой droword. мягкая угроза.",
                  de: "scrollen ≠ lernen. öffne droword. soft threat.",
                  es: "scroll ≠ estudiar. abre droword. amenaza soft.",
                  fr: "scroll ≠ étude. ouvre droword. soft threat.",
                  ja: "スクロール≠勉強。droword開いて。やさしい脅し。",
                  ko: "스크롤 ≠ 공부. droword 열어. 소프트 협박.",
                  ar: "السك롤 ≠ دراسة. افتح droword. تهديد لطيف.",
                  it: "scroll ≠ studio. apri droword. soft threat.",
                  zhHans: "刷手机 ≠ 学习。打开 droword。温柔威胁。",
                  zhHant: "刷手機 ≠ 學習。打開 droword。溫柔威脅。",
                  pt: "scroll ≠ estudar. abre o droword. soft threat.")
            ),
            (
                L("we’re not ghosting you",
                  ru: "мы тебя не гоустим",
                  de: "wir ghosten dich nicht",
                  es: "no te estamos ghosteando",
                  fr: "on te ghost pas",
                  ja: "ゴーストしてないよ",
                  ko: "우리가 널 고스트한 게 아냐",
                  ar: "مو نحن عم نغوستك",
                  it: "non ti stiamo ghostando",
                  zhHans: "不是我们在 ghost 你",
                  zhHant: "不是我們在 ghost 你",
                  pt: "não te estamos a ghostar"),
                L("…you ghosted the vocab though. come back.",
                  ru: "…а вот слова ты загоустил. возвращайся.",
                  de: "…aber du hast die vokabeln geghostet. komm zurück.",
                  es: "…pero tú ghosteaste el vocabulario. vuelve.",
                  fr: "…par contre tu as ghost le vocab. reviens.",
                  ja: "…でも語彙をゴーストしたのは君。戻ってきて。",
                  ko: "…근데 단어는 네가 고스트함. 돌아와.",
                  ar: "…بس أنت غوست الكلمات. ارجع.",
                  it: "…però hai ghostato il vocab. torna.",
                  zhHans: "…是你 ghost 了单词。回来。",
                  zhHant: "…是你 ghost 了單字。回來。",
                  pt: "…mas tu ghostaste o vocabulário. volta.")
            ),
            (
                L("main character energy check",
                  ru: "чек main character энергии",
                  de: "main character energy check",
                  es: "check de energía main character",
                  fr: "check main character energy",
                  ja: "メインキャラ能量チェック",
                  ko: "메인 캐릭터 에너지 체크",
                  ar: "تشيك طاقة البروتاغونيست",
                  it: "check energia main character",
                  zhHans: "主角光环点名",
                  zhHant: "主角光環點名",
                  pt: "check de energia main character"),
                L("side characters scroll. you open the lesson. go.",
                  ru: "сайд-персонажи скроллят. ты открываешь урок. погнали.",
                  de: "nebenfiguren scrollen. du öffnest die lesson. go.",
                  es: "los secundarios scrollean. tú abres la lección. go.",
                  fr: "les seconds rôles scrollent. toi tu ouvres la leçon. go.",
                  ja: "脇役はスクロール。君はレッスン開く。行け。",
                  ko: "조연은 스크롤. 너는 레슨 연다. 가.",
                  ar: "الثانويين بيسكرولوا. أنت بتفتح الدرس. يلا.",
                  it: "i secondari scrollano. tu apri la lezione. go.",
                  zhHans: "配角在刷。你打开课。走。",
                  zhHant: "配角在刷。你打開課。走。",
                  pt: "secundários fazem scroll. tu abres a lição. go.")
            ),
            (
                L("touch grass… after one word",
                  ru: "touch grass… после одного слова",
                  de: "touch grass… nach einem wort",
                  es: "touch grass… después de una palabra",
                  fr: "touch grass… après un mot",
                  ja: "touch grass…でも1語のあとで",
                  ko: "touch grass… 단어 하나 하고",
                  ar: "touch grass… بعد كلمة",
                  it: "touch grass… dopo una parola",
                  zhHans: "touch grass…先学一个词",
                  zhHant: "touch grass…先學一個詞",
                  pt: "touch grass… depois de uma palavra"),
                L("deal? tiny review then free. we’re watching.",
                  ru: "договор? короткое ревью — и свободен. мы смотрим.",
                  de: "deal? mini-review dann frei. wir schauen zu.",
                  es: "¿trato? mini review y libre. te estamos mirando.",
                  fr: "deal ? mini révi puis libre. on regarde.",
                  ja: "取引？ちょっと復習してから自由。見てるよ。",
                  ko: "딜? 짧게 복습하고 자유. 우리가 보고 있어.",
                  ar: "صفقة؟ مراجعة صغيرة وبعدين حر. عم نراقب.",
                  it: "affare? mini ripasso e poi libero. stiamo guardando.",
                  zhHans: "成交？短复习然后自由。我们看着呢。",
                  zhHant: "成交？短複習然後自由。我們看著呢。",
                  pt: "trato? mini revisão e depois livre. estamos a ver.")
            ),
            (
                L("your words left on read",
                  ru: "твои слова left on read",
                  de: "deine wörter left on read",
                  es: "tus palabras left on read",
                  fr: "tes mots left on read",
                  ja: "単語が既読スルーされてる",
                  ko: "단어들이 읽씹당함",
                  ar: "كلماتك left on read",
                  it: "le tue parole left on read",
                  zhHans: "单词已读不回",
                  zhHant: "單字已讀不回",
                  pt: "as tuas palavras left on read"),
                L("rude. open up and reply with a review.",
                  ru: "грубо. открой и ответь ревью.",
                  de: "frech. öffne und antworte mit einem review.",
                  es: "qué grosero. abre y responde con un repaso.",
                  fr: "vrai. ouvre et réponds avec une révi.",
                  ja: "失礼。開いて復習で返信して。",
                  ko: "무례함. 열고 복습으로 답장해.",
                  ar: "وقح. افتح ورد بمراجعة.",
                  it: "scortese. apri e rispondi con un ripasso.",
                  zhHans: "过分。打开用复习回一下。",
                  zhHant: "過分。打開用複習回一下。",
                  pt: "grosseiro. abre e responde com uma revisão.")
            ),
            (
                L("soft threat unlocked",
                  ru: "мягкая угроза unlocked",
                  de: "soft threat freigeschaltet",
                  es: "amenaza soft desbloqueada",
                  fr: "soft threat débloqué",
                  ja: "やさしい脅し解放",
                  ko: "소프트 협박 해금",
                  ar: "تهديد لطيف مفتوح",
                  it: "soft threat sbloccata",
                  zhHans: "温柔威胁已解锁",
                  zhHant: "溫柔威脅已解鎖",
                  pt: "soft threat desbloqueada"),
                L("open droword or we keep vibing in your notifications.",
                  ru: "открой droword или мы продолжим тусить в пушах.",
                  de: "öffne droword oder wir vibieren weiter in deinen notifs.",
                  es: "abre droword o seguimos vibing en tus notifs.",
                  fr: "ouvre droword ou on continue de vibes dans tes notifs.",
                  ja: "droword開かないと通知でバイブス続けるよ。",
                  ko: "droword 안 열면 알림에서 계속 바이브 함.",
                  ar: "افتح droword أو بنكمل فايبنغ بالإشعارات.",
                  it: "apri droword o continuiamo a vibare nelle notif.",
                  zhHans: "打开 droword，不然我们继续在通知里蹦迪。",
                  zhHant: "打開 droword，不然我們繼續在通知裡蹦迪。",
                  pt: "abre o droword ou continuamos a vibar nas notifs.")
            ),
            (
                L("bro the streak is dramatizing",
                  ru: "бро серия уже драматизирует",
                  de: "bro die serie macht drama",
                  es: "bro la racha está dramatizando",
                  fr: "bro la série fait du drama",
                  ja: "連続がドラマ化してる",
                  ko: "브로 연속이 드라마 치는 중",
                  ar: "برو السلسلة عم تعمل دراما",
                  it: "bro la serie sta dramatizzando",
                  zhHans: "连续打卡开始演了",
                  zhHant: "連續打卡開始演了",
                  pt: "bro a sequência está a dramatizar"),
                L("one word. save the arc. be the plot armor.",
                  ru: "одно слово. спаси арку. будь plot armor.",
                  de: "ein wort. rette den arc. sei plot armor.",
                  es: "una palabra. salva el arco. sé el plot armor.",
                  fr: "un mot. sauve l’arc. sois le plot armor.",
                  ja: "1語。アークを救え。plot armorになれ。",
                  ko: "단어 하나. 아크 구해. plot armor 돼.",
                  ar: "كلمة. أنقذ القوس. كن الـ plot armor.",
                  it: "una parola. salva l’arco. sii il plot armor.",
                  zhHans: "一个词。救剧情。当护体光环。",
                  zhHant: "一個詞。救劇情。當護體光環。",
                  pt: "uma palavra. salva o arco. sê o plot armor.")
            ),
            (
                L("it’s giving neglected dictionary",
                  ru: "it’s giving заброшенный словарь",
                  de: "it’s giving vernachlässigtes wörterbuch",
                  es: "it’s giving diccionario abandonado",
                  fr: "it’s giving dico négligé",
                  ja: "放置辞書感出てる",
                  ko: "방치된 사전 vibes",
                  ar: "it’s giving قاموس مهمل",
                  it: "it’s giving dizionario abbandonato",
                  zhHans: "it’s giving 被冷落的词典",
                  zhHant: "it’s giving 被冷落的詞典",
                  pt: "it’s giving dicionário abandonado"),
                L("fix that. two minutes. we believe in you (kinda).",
                  ru: "пофикси. две минуты. мы в тебя верим (типа).",
                  de: "fix das. zwei minuten. wir glauben an dich (irgendwie).",
                  es: "arrégalo. dos minutos. creemos en ti (tipo).",
                  fr: "fix ça. deux minutes. on croit en toi (genre).",
                  ja: "直して。2分。信じてる(まあ少し)。",
                  ko: "고쳐. 2분. 믿어 (약간).",
                  ar: "صلّحها. دقيقتين. منآمن فيك (نوعًا).",
                  it: "sistema. due minuti. crediamo in te (tipo).",
                  zhHans: "修一下。两分钟。我们信你(大概)。",
                  zhHant: "修一下。兩分鐘。我們信你(大概)。",
                  pt: "arranja isso. dois minutos. acreditamos em ti (tipo).")
            ),
            (
                L("no cap you need this",
                  ru: "no cap тебе это надо",
                  de: "no cap du brauchst das",
                  es: "no cap necesitas esto",
                  fr: "no cap t’as besoin de ça",
                  ja: "マジでこれ必要",
                  ko: "노캡 너 이거 필요함",
                  ar: "no cap أنت محتاج هيدا",
                  it: "no cap ti serve questo",
                  zhHans: "认真的你需要这个",
                  zhHant: "認真的你需要這個",
                  pt: "no cap precisas disto"),
                L("tiny session. big brain. open before the vibes expire.",
                  ru: "короткая сессия. big brain. открой пока вайб не сдох.",
                  de: "mini-session. big brain. öffne bevor die vibes sterben.",
                  es: "mini sesión. big brain. abre antes de que mueran los vibes.",
                  fr: "mini session. big brain. ouvre avant que les vibes meurent.",
                  ja: "短いセッション。big brain。バイブス消える前に開けて。",
                  ko: "짧은 세션. big brain. 바이브 죽기 전에 열어.",
                  ar: "جلسة صغيرة. big brain. افتح قبل ما تموت الفايبس.",
                  it: "mini sessione. big brain. apri prima che muoiano le vibes.",
                  zhHans: "短练习。大聪明。氛围散之前打开。",
                  zhHant: "短練習。大聰明。氛圍散之前打開。",
                  pt: "mini sessão. big brain. abre antes de as vibes morrerem.")
            ),
            (
                L("we came to collect",
                  ru: "мы пришли забрать",
                  de: "wir sind zum eintreiben da",
                  es: "vinimos a cobrar",
                  fr: "on est venus collecter",
                  ja: "取り立てに来た",
                  ko: "받으러 왔어",
                  ar: "جئنا نحصّل",
                  it: "siamo venuti a riscuotere",
                  zhHans: "我们来催债了",
                  zhHant: "我們來催債了",
                  pt: "viemos cobrar"),
                L("debt = one review. interest = more notifs. pay up.",
                  ru: "долг = одно ревью. проценты = ещё пуши. плати.",
                  de: "schuld = ein review. zinsen = mehr notifs. zahl.",
                  es: "deuda = un repaso. interés = más notifs. paga.",
                  fr: "dette = une révi. intérêts = plus de notifs. paye.",
                  ja: "借金＝復習1回。利息＝通知増。払って。",
                  ko: "빚 = 복습 한 번. 이자 = 알림 더. 갚아.",
                  ar: "الدين = مراجعة. الفايدة = إشعارات زيادة. ادفع.",
                  it: "debito = un ripasso. interessi = più notif. paga.",
                  zhHans: "债 = 一次复习。利息 = 更多通知。还。",
                  zhHant: "債 = 一次複習。利息 = 更多通知。還。",
                  pt: "dívida = uma revisão. juros = mais notifs. paga.")
            ),
            (
                L("this is your villain origin",
                  ru: "это твой villain origin",
                  de: "das ist dein villain origin",
                  es: "este es tu villain origin",
                  fr: "c’est ton villain origin",
                  ja: "これがヴィラン起源",
                  ko: "이게 네 빌런 오리진",
                  ar: "هيدا أصل الشرير تبعك",
                  it: "questa è la tua villain origin",
                  zhHans: "这是你的反派起源",
                  zhHant: "這是你的反派起源",
                  pt: "esta é a tua villain origin"),
                L("skip today → lore. open now → redemption arc. choose.",
                  ru: "пропусти сегодня → лор. открой → redemption arc. выбирай.",
                  de: "heute skippen → lore. jetzt öffnen → redemption arc. wähl.",
                  es: "saltar hoy → lore. abrir ahora → redemption arc. elige.",
                  fr: "skip aujourd’hui → lore. ouvre → redemption arc. choisis.",
                  ja: "今日スキップ→lore。今開く→redemption arc。選べ。",
                  ko: "오늘 스킵 → lore. 지금 열기 → redemption arc. 골라.",
                  ar: "فوت اليوم → lore. افتح هلأ → redemption arc. اختار.",
                  it: "salta oggi → lore. apri ora → redemption arc. scegli.",
                  zhHans: "今天跳过 → lore。现在打开 → 救赎弧。选。",
                  zhHant: "今天跳過 → lore。現在打開 → 救贖弧。選。",
                  pt: "saltar hoje → lore. abrir agora → redemption arc. escolhe.")
            ),
        ])
    }



    static func inactivity(atIndex index: Int) -> (title: String, body: String) {
        let pairs: [([String: String], [String: String])] = [
            (
                L("ok so you’re ghosting",
                  ru: "ок так ты гоустишь",
                  de: "ok also du ghostest",
                  es: "ok así que estás ghosteando",
                  fr: "ok donc tu ghost",
                  ja: "なるほどゴーストしてる",
                  ko: "오케이 너 고스트 중이구나",
                  ar: "طيب يعني عم تغوست",
                  it: "ok quindi stai ghostando",
                  zhHans: "所以你在 ghost",
                  zhHant: "所以你在 ghost",
                  pt: "ok então estás a ghostar"),
                L("a few days silent. we noticed. soft threat: open.",
                  ru: "пара дней тишины. мы заметили. мягкая угроза: открой.",
                  de: "ein paar tage still. wir haben’s gemerkt. soft threat: öffne.",
                  es: "unos días en silencio. lo notamos. amenaza soft: abre.",
                  fr: "quelques jours de silence. on a vu. soft threat: ouvre.",
                  ja: "数日沈黙。気づいたよ。やさしい脅し：開けて。",
                  ko: "며칠 침묵. 우리가 봄. 소프트 협박: 열어.",
                  ar: "كم يوم صمت. انتبهنا. تهديد لطيف: افتح.",
                  it: "qualche giorno di silenzio. l’abbiamo notato. soft threat: apri.",
                  zhHans: "安静几天了。我们看见了。温柔威胁：打开。",
                  zhHant: "安靜幾天了。我們看見了。溫柔威脅：打開。",
                  pt: "uns dias de silêncio. notámos. soft threat: abre.")
            ),
            (
                L("streak is in the group chat crying",
                  ru: "серия плачет в групповом чате",
                  de: "die serie weint im gruppenchat",
                  es: "la racha llora en el group chat",
                  fr: "la série pleure dans le group chat",
                  ja: "連続がグループチャットで泣いてる",
                  ko: "연속이 단톡에서 울고 있음",
                  ar: "السلسلة عم تبكي بالجروب",
                  it: "la serie piange nel group chat",
                  zhHans: "连续打卡在群聊里哭",
                  zhHant: "連續打卡在群聊裡哭",
                  pt: "a sequência está a chorar no group chat"),
                L("a week without vocab. one word = comeback lore.",
                  ru: "неделя без слов. одно слово = comeback lore.",
                  de: "eine woche ohne vokabeln. ein wort = comeback lore.",
                  es: "una semana sin vocab. una palabra = comeback lore.",
                  fr: "une semaine sans vocab. un mot = comeback lore.",
                  ja: "1週間ぶりの語彙。1語＝カムバックlore。",
                  ko: "일주일 단어 공백. 하나 = 컴백 lore.",
                  ar: "أسبوع بلا كلمات. كلمة = كومباك lore.",
                  it: "una settimana senza vocab. una parola = comeback lore.",
                  zhHans: "一周没碰单词。一个词 = 回归 lore。",
                  zhHant: "一週沒碰單字。一個詞 = 回歸 lore。",
                  pt: "uma semana sem vocab. uma palavra = comeback lore.")
            ),
            (
                L("we kept your seat warm (creepy)",
                  ru: "мы грели тебе место (крипово)",
                  de: "wir hielten deinen platz warm (creepy)",
                  es: "guardamos tu asiento (creepy)",
                  fr: "on a gardé ta place (creepy)",
                  ja: "席温めてたよ(ちょい不気味)",
                  ko: "자리 따뜻하게 지켜둠 (좀 소름)",
                  ar: "دفّينا مقعدك (كريبي)",
                  it: "abbiamo tenuto il posto caldo (creepy)",
                  zhHans: "座位给你捂热了(有点诡异)",
                  zhHant: "座位給你捂熱了(有點詭異)",
                  pt: "aqueciemos o teu lugar (creepy)"),
                L("two weeks away. no judgment. just… open before we escalate.",
                  ru: "две недели. без осуждения. просто… открой до эскалации.",
                  de: "zwei wochen weg. kein urteil. einfach… öffne bevor wir eskalieren.",
                  es: "dos semanas fuera. sin juicio. solo… abre antes de que escalemos.",
                  fr: "deux semaines absentes. sans jugement. juste… ouvre avant qu’on scale.",
                  ja: "2週間ぶり。責めない。ただ…エスカレート前に開けて。",
                  ko: "2주 자리비움. 탓 안 해. 그냥… 에스컬레이트 전에 열어.",
                  ar: "أسبوعين برا. بدون حكم. بس… افتح قبل ما نصعّد.",
                  it: "due settimane via. nessun giudizio. solo… apri prima che scalaimo.",
                  zhHans: "两周没来。不评判。只是…升级前打开。",
                  zhHant: "兩週沒來。不評判。只是…升級前打開。",
                  pt: "duas semanas fora. sem juízos. só… abre antes de escalarmos.")
            ),
            (
                L("long break? soft reboot unlocked",
                  ru: "долгий перерыв? soft reboot unlocked",
                  de: "lange pause? soft reboot freigeschaltet",
                  es: "¿pausa larga? soft reboot desbloqueado",
                  fr: "longue pause ? soft reboot débloqué",
                  ja: "長い休み？soft reboot解放",
                  ko: "긴 휴식? soft reboot 해금",
                  ar: "استراحة طويلة؟ soft reboot مفتوح",
                  it: "lunga pausa? soft reboot sbloccata",
                  zhHans: "长假？温柔重启已解锁",
                  zhHant: "長假？溫柔重啟已解鎖",
                  pt: "pausa longa? soft reboot desbloqueado"),
                L("a month offline. start with one word. we won’t rat you out.",
                  ru: "месяц оффлайн. начни с одного слова. мы не сдадим.",
                  de: "einen monat offline. fang mit einem wort an. wir verpetzen dich nicht.",
                  es: "un mes offline. empieza con una palabra. no te delatamos.",
                  fr: "un mois offline. commence par un mot. on te balance pas.",
                  ja: "1か月オフ。1語から。チクらないよ。",
                  ko: "한 달 오프라인. 단어 하나로 시작. 고자질 안 함.",
                  ar: "شهر أوفلاين. ابدأ بكلمة. مش هنفضحك.",
                  it: "un mese offline. parti da una parola. non ti spiattelliamo.",
                  zhHans: "离线一个月。从一个词开始。我们不告密。",
                  zhHant: "離線一個月。從一個詞開始。我們不告密。",
                  pt: "um mês offline. começa com uma palavra. não te denunciamos.")
            ),
            (
                L("scrolling again? we see you",
                  ru: "опять скроллишь? мы видим",
                  de: "wieder am scrollen? wir sehen dich",
                  es: "¿scrolleando otra vez? te vemos",
                  fr: "encore en train de scroller ? on te voit",
                  ja: "またスクロール？見てるよ",
                  ko: "또 스크롤? 우리가 봄",
                  ar: "عم تسكرول تاني؟ عم نشوفك",
                  it: "di nuovo a scrollare? ti vediamo",
                  zhHans: "又在刷？我们看见了",
                  zhHant: "又在刷？我們看見了",
                  pt: "outra vez a fazer scroll? vemos-te"),
                L("touch grass later. open droword first. deal or more notifs.",
                  ru: "touch grass потом. сначала droword. deal или ещё пуши.",
                  de: "touch grass später. erst droword. deal oder mehr notifs.",
                  es: "touch grass después. primero droword. trato o más notifs.",
                  fr: "touch grass plus tard. droword d’abord. deal ou plus de notifs.",
                  ja: "touch grassは後で。先にdroword。取引か通知増。",
                  ko: "touch grass는 나중에. 먼저 droword. 딜 아니면 알림 더.",
                  ar: "touch grass بعدين. droword أول. صفقة أو إشعارات زيادة.",
                  it: "touch grass dopo. prima droword. affare o più notif.",
                  zhHans: "touch grass 稍后。先打开 droword。成交还是更多通知。",
                  zhHant: "touch grass 稍後。先打開 droword。成交還是更多通知。",
                  pt: "touch grass depois. droword primeiro. trato ou mais notifs.")
            ),
            (
                L("plot twist: we missed you (ew feelings)",
                  ru: "плот твист: мы соскучились (фу чувства)",
                  de: "plot twist: du fehlst uns (ew gefühle)",
                  es: "plot twist: te extrañamos (ew sentimientos)",
                  fr: "plot twist: tu nous as manqué (ew feelings)",
                  ja: "どんでん返し：会いたかった(気持ちキモ)",
                  ko: "반전: 보고 싶었어 (으 감정)",
                  ar: "تويست: اشتقنالك (يو مشاعر)",
                  it: "plot twist: ci sei mancato (ew feelings)",
                  zhHans: "剧情反转：我们想你了(呕情绪)",
                  zhHant: "劇情反轉：我們想你了(嘔情緒)",
                  pt: "plot twist: sentimos a tua falta (ew feelings)"),
                L("come back. your words are being dramatic without you.",
                  ru: "возвращайся. слова без тебя устраивают драму.",
                  de: "komm zurück. deine wörter machen drama ohne dich.",
                  es: "vuelve. tus palabras hacen drama sin ti.",
                  fr: "reviens. tes mots font du drama sans toi.",
                  ja: "戻って。単語が君なしでドラマしてる。",
                  ko: "돌아와. 단어들이 너 없이 드라마 침.",
                  ar: "ارجع. كلماتك عم تعمل دراما بدونك.",
                  it: "torna. le tue parole fanno drama senza di te.",
                  zhHans: "回来。单词没你在演大戏。",
                  zhHant: "回來。單字沒你在演大戲。",
                  pt: "volta. as tuas palavras estão a fazer drama sem ti.")
            ),
        ]
        let i = min(max(index, 0), pairs.count - 1)
        return (t(pairs[i].0), t(pairs[i].1))
    }



    static func pickReviewTitle() -> String {
        let titles: [[String: String]] = [
            L("words are in your dms",
              ru: "слова у тебя в димах",
              de: "wörter sind in deinen dms",
              es: "las palabras están en tus dms",
              fr: "les mots sont dans tes dms",
              ja: "単語がDMに来てる",
              ko: "단어들이 DM에 있음",
              ar: "الكلمات بـ dms تبعك",
              it: "le parole sono nelle tue dm",
              zhHans: "单词在你私信里",
              zhHant: "單字在你私訊裡",
              pt: "as palavras estão nas tuas dms"),
            L("review or we escalate",
              ru: "ревью или эскалируем",
              de: "review oder wir eskalieren",
              es: "repasa o escalamos",
              fr: "révise ou on scale",
              ja: "復習しないとエスカレート",
              ko: "복습 안 하면 에스컬레이트",
              ar: "راجع أو منصعّد",
              it: "ripassa o scalaimo",
              zhHans: "复习不然我们升级",
              zhHant: "複習不然我們升級",
              pt: "revisa ou escalamos"),
            L("memory check (no cap)",
              ru: "чек памяти (no cap)",
              de: "gedächtnis-check (no cap)",
              es: "chequeo de memoria (no cap)",
              fr: "check mémoire (no cap)",
              ja: "記憶チェック(マジ)",
              ko: "기억 체크 (노캡)",
              ar: "تشيك ذاكرة (no cap)",
              it: "check memoria (no cap)",
              zhHans: "记忆点名(认真)",
              zhHant: "記憶點名(認真)",
              pt: "check de memória (no cap)"),
            L("your streak wants receipts",
              ru: "серия хочет receipts",
              de: "deine serie will receipts",
              es: "tu racha quiere receipts",
              fr: "ta série veut des receipts",
              ja: "連続が証拠求めてる",
              ko: "연속이 영수증 원함",
              ar: "سلسلتك بدها إثبات",
              it: "la serie vuole receipts",
              zhHans: "连续打卡要收据",
              zhHant: "連續打卡要收據",
              pt: "a sequência quer receipts"),
            L("soft threat: open the deck",
              ru: "мягкая угроза: открой колоду",
              de: "soft threat: öffne das deck",
              es: "amenaza soft: abre el mazo",
              fr: "soft threat: ouvre le deck",
              ja: "やさしい脅し：デッキ開けて",
              ko: "소프트 협박: 덱 열어",
              ar: "تهديد لطيف: افتح الدك",
              it: "soft threat: apri il mazzo",
              zhHans: "温柔威胁：打开牌组",
              zhHant: "溫柔威脅：打開牌組",
              pt: "soft threat: abre o baralho"),
            L("they’re due and they’re dramatic",
              ru: "они due и они драматичные",
              de: "sie sind fällig und dramatisch",
              es: "están due y están dramatic",
              fr: "ils sont due et dramatiques",
              ja: "期限切れでドラマチック",
              ko: "due인데 드라마틱함",
              ar: "due ودراميين",
              it: "sono due e sono dramatic",
              zhHans: "到期了而且很戏剧",
              zhHant: "到期了而且很戲劇",
              pt: "estão due e estão dramatic"),
        ]
        return t(titles[dayIndex % titles.count])
    }

    static func reviewBody(count: Int) -> String {
        if count == 1 {
            return t(L(
                "1 word due. won’t take long. we’re watching.",
                ru: "1 слово due. много не займёт. мы смотрим.",
                de: "1 wort due. dauert nicht. wir schauen zu.",
                es: "1 palabra due. no toma mucho. te miramos.",
                fr: "1 mot due. ça prendra pas longtemps. on regarde.",
                ja: "1語 due。すぐ終わる。見てるよ。",
                ko: "단어 1개 due. 오래 안 걸려. 보고 있어.",
                ar: "كلمة due. ما رح يطول. عم نراقب.",
                it: "1 parola due. non ci vuole molto. stiamo guardando.",
                zhHans: "1 个词 due。不会久。我们看着。",
                zhHant: "1 個詞 due。不會久。我們看著。",
                pt: "1 palavra due. não demora. estamos a ver."
            ))
        }

        let ruWords = russianWordsReady(count)
        return t(L(
            "{COUNT} words due. quick hit then you’re free (for now).",
            ru: "\(count) \(ruWords). быстрый заход — и свободен (пока).",
            de: "{COUNT} wörter due. quick hit dann frei (erstmal).",
            es: "{COUNT} palabras due. golpe rápido y libre (por ahora).",
            fr: "{COUNT} mots due. quick hit puis libre (pour l’instant).",
            ja: "{COUNT}語 due。サクッとやって自由(今のところ)。",
            ko: "{COUNT}개 due. 빠르게 하고 자유 (일단).",
            ar: "{COUNT} كلمات due. ضربة سريعة وبعدين حر (هلأ).",
            it: "{COUNT} parole due. colpo veloce e poi libero (per ora).",
            zhHans: "{COUNT} 个词 due。速通然后自由(暂时)。",
            zhHant: "{COUNT} 個詞 due。速通然後自由(暫時)。",
            pt: "{COUNT} palavras due. hit rápido e depois livre (por agora)."
        )).replacingOccurrences(of: "{COUNT}", with: "\(count)")
    }

    private static func russianWordsReady(_ count: Int) -> String {
        let n = abs(count) % 100
        let n1 = n % 10
        if n >= 11 && n <= 14 {
            return "слов due"
        }
        switch n1 {
        case 1:
            return "слово due"
        case 2, 3, 4:
            return "слова due"
        default:
            return "слов due"
        }
    }

    static func vocabBody(
        transcription: String?,
        translation: String?,
        showTranscription: Bool,
        showTranslation: Bool
    ) -> String {
        var parts: [String] = []
        if showTranscription, let transcription, !transcription.isEmpty {
            parts.append("[\(transcription)]")
        }
        if showTranslation, let translation, !translation.isEmpty {
            parts.append(translation)
        }
        if parts.isEmpty {
            return t(L(
                "be honest… do you remember this one? soft threat.",
                ru: "честно… помнишь это? мягкая угроза.",
                de: "sei ehrlich… erinnerst du dich? soft threat.",
                es: "sé honesto… ¿recuerdas esta? amenaza soft.",
                fr: "sois honnête… tu te souviens ? soft threat.",
                ja: "正直に…覚えてる？やさしい脅し。",
                ko: "솔직히… 이거 기억나? 소프트 협박.",
                ar: "بصراحة… بتتذكر هيدي؟ تهديد لطيف.",
                it: "onesto… ti ricordi questa? soft threat.",
                zhHans: "说实话…还记得这个吗？温柔威胁。",
                zhHant: "說實話…還記得這個嗎？溫柔威脅。",
                pt: "sê honesto… lembras-te desta? soft threat."
            ))
        }
        return parts.joined(separator: " · ")
    }



    static func streakMilestone(for streak: Int) -> (title: String, body: String) {
        switch streak {
        case 7:
            return (
                t(L("7-day arc unlocked",
                    ru: "7-дневная арка unlocked",
                    de: "7-tage-arc freigeschaltet",
                    es: "arco de 7 días desbloqueado",
                    fr: "arc 7 jours débloqué",
                    ja: "7日アーク解放",
                    ko: "7일 아크 해금",
                    ar: "قوس ٧ أيام مفتوح",
                    it: "arco 7 giorni sbloccato",
                    zhHans: "7 日弧线已解锁",
                    zhHant: "7 日弧線已解鎖",
                    pt: "arco de 7 dias desbloqueado")),
                t(L("one week main character. the streak is thriving.",
                    ru: "неделя main character. серия thrives.",
                    de: "eine woche main character. die serie thrived.",
                    es: "una semana main character. la racha thrives.",
                    fr: "une semaine main character. la série thrives.",
                    ja: "1週間メインキャラ。連続が輝いてる。",
                    ko: "일주일 메인 캐릭터. 연속 thriving.",
                    ar: "أسبوع بروتاغونيست. السلسلة thrives.",
                    it: "una settimana main character. la serie thrives.",
                    zhHans: "一周主角。连续打卡在发光。",
                    zhHant: "一週主角。連續打卡在發光。",
                    pt: "uma semana main character. a sequência thrives."))
            )
        case 30:
            return (
                t(L("30 days. no cap.",
                    ru: "30 дней. no cap.",
                    de: "30 tage. no cap.",
                    es: "30 días. no cap.",
                    fr: "30 jours. no cap.",
                    ja: "30日。マジ。",
                    ko: "30일. 노캡.",
                    ar: "٣٠ يوم. no cap.",
                    it: "30 giorni. no cap.",
                    zhHans: "30 天。认真的。",
                    zhHant: "30 天。認真的。",
                    pt: "30 dias. no cap.")),
                t(L("full month lore. the group chat is screaming.",
                    ru: "месяц лора. групповой чат орёт.",
                    de: "voller monats-lore. der gruppenchat schreit.",
                    es: "lore de un mes. el group chat grita.",
                    fr: "lore d’un mois. le group chat hurle.",
                    ja: "まる1か月のlore。グループチャットが叫んでる。",
                    ko: "한 달 lore. 단톡이 비명 중.",
                    ar: "lore شهر كامل. الجروب عم يصرخ.",
                    it: "lore di un mese. il group chat urla.",
                    zhHans: "整月 lore。群聊在尖叫。",
                    zhHant: "整月 lore。群聊在尖叫。",
                    pt: "lore de um mês. o group chat está a gritar."))
            )
        case 100:
            return (
                t(L("100 days. legend behavior",
                    ru: "100 дней. legend behavior",
                    de: "100 tage. legend behavior",
                    es: "100 días. legend behavior",
                    fr: "100 jours. legend behavior",
                    ja: "100日。レジェンド挙動",
                    ko: "100일. 레전드 행동",
                    ar: "١٠٠ يوم. سلوك أسطوري",
                    it: "100 giorni. legend behavior",
                    zhHans: "100 天。传奇行为",
                    zhHant: "100 天。傳奇行為",
                    pt: "100 dias. legend behavior")),
                t(L("your consistency is unhinged (in a good way).",
                    ru: "твоя дисциплина unhinged (в хорошем смысле).",
                    de: "deine konstanz ist unhinged (im guten sinne).",
                    es: "tu constancia está unhinged (en el buen sentido).",
                    fr: "ta régularité est unhinged (dans le bon sens).",
                    ja: "継続力やばい(いい意味で)。",
                    ko: "꾸준함이 언힌지드 (좋은 뜻으로).",
                    ar: "ثباتك مجنون (بمعنى حلو).",
                    it: "la tua costanza è unhinged (in senso buono).",
                    zhHans: "你的坚持有点疯(褒义)。",
                    zhHant: "你的堅持有點瘋(褒義)。",
                    pt: "a tua consistência está unhinged (no bom sentido)."))
            )
        case 365:
            return (
                t(L("365. full year. we’re obsessed",
                    ru: "365. целый год. мы obsessed",
                    de: "365. volles jahr. wir sind obsessed",
                    es: "365. año completo. estamos obsessed",
                    fr: "365. année pleine. on est obsessed",
                    ja: "365。まる1年。沼ってる",
                    ko: "365. 꼬박 일 년. 우리가 obsessed",
                    ar: "٣٦٥. سنة كاملة. نحن obsessed",
                    it: "365. anno pieno. siamo obsessed",
                    zhHans: "365。整年。我们上头了",
                    zhHant: "365。整年。我們上頭了",
                    pt: "365. ano completo. estamos obsessed")),
                t(L("you didn’t skip the lore. plot armor permanent. huge.",
                    ru: "ты не скипнул лор. plot armor навсегда. огромно.",
                    de: "du hast den lore nicht geskippt. plot armor permanent. riesig.",
                    es: "no saltaste el lore. plot armor permanente. enorme.",
                    fr: "tu n’as pas skip le lore. plot armor permanent. énorme.",
                    ja: "loreスキップしなかった。plot armor永久。でかい。",
                    ko: "lore 안 스킵함. plot armor 영구. 거대.",
                    ar: "ما فوتّ الـ lore. plot armor دائم. ضخم.",
                    it: "non hai skippato il lore. plot armor permanente. enorme.",
                    zhHans: "你没跳过 lore。永久护体。巨大。",
                    zhHant: "你沒跳過 lore。永久護體。巨大。",
                    pt: "não saltaste o lore. plot armor permanente. enorme."))
            )
        default:
            return (
                t(L("new streak milestone unlocked",
                    ru: "новый рубеж серии unlocked",
                    de: "neuer serien-meilenstein freigeschaltet",
                    es: "nuevo hito de racha desbloqueado",
                    fr: "nouveau jalon de série débloqué",
                    ja: "連続マイルストーン解放",
                    ko: "연속 마일스톤 해금",
                    ar: "محطة سلسلة جديدة مفتوحة",
                    it: "nuovo traguardo serie sbloccato",
                    zhHans: "连续打卡新里程碑已解锁",
                    zhHant: "連續打卡新里程碑已解鎖",
                    pt: "novo marco da sequência desbloqueado")),
                t(L("{STREAK} days. the arc continues. don’t drop the bag.",
                    ru: "{STREAK} дней. арка продолжается. не дропни bag.",
                    de: "{STREAK} tage. der arc geht weiter. drop the bag nicht.",
                    es: "{STREAK} días. el arco sigue. no drops the bag.",
                    fr: "{STREAK} jours. l’arc continue. drop pas the bag.",
                    ja: "{STREAK}日。アーク続く。bag落とすな。",
                    ko: "{STREAK}일. 아크 계속. bag 드롭 마.",
                    ar: "{STREAK} يوم. القوس مستمر. ما تفلّت الـ bag.",
                    it: "{STREAK} giorni. l’arco continua. non droppare the bag.",
                    zhHans: "{STREAK} 天。剧情继续。别掉包。",
                    zhHant: "{STREAK} 天。劇情繼續。別掉包。",
                    pt: "{STREAK} dias. o arco continua. não drops the bag."))
                    .replacingOccurrences(of: "{STREAK}", with: "\(streak)")
            )
        }
    }



    static func pickGoal() -> (title: String, body: String) {
        pick([
            (
                L("daily goal cleared. bag secured",
                  ru: "дневная цель закрыта. bag secured",
                  de: "tagesziel klar. bag secured",
                  es: "meta diaria hecha. bag secured",
                  fr: "objectif du jour validé. bag secured",
                  ja: "今日の目標クリア。bag確保",
                  ko: "오늘 목표 클리어. bag secured",
                  ar: "هدف اليوم خلص. bag secured",
                  it: "obiettivo giornaliero fatto. bag secured",
                  zhHans: "今日目标完成。包拿到了",
                  zhHant: "今日目標完成。包拿到了",
                  pt: "objetivo diário feito. bag secured"),
                L("you hit today’s word goal. main character wins again.",
                  ru: "цель по словам на сегодня закрыта. main character снова победил.",
                  de: "wortziel von heute geschafft. main character gewinnt wieder.",
                  es: "cumpliste la meta de palabras de hoy. main character gana otra vez.",
                  fr: "objectif mots d’aujourd’hui atteint. main character gagne encore.",
                  ja: "今日の単語目標クリア。メインキャラまた勝ち。",
                  ko: "오늘 단어 목표 달성. 메인 캐릭터 또 승.",
                  ar: "وصلت هدف كلمات اليوم. البروتاغونيست فاز تاني.",
                  it: "obiettivo parole di oggi fatto. main character vince ancora.",
                  zhHans: "今天单词目标完成。主角又赢了。",
                  zhHant: "今天單字目標完成。主角又贏了。",
                  pt: "objetivo de palavras de hoje feito. main character ganha outra vez.")
            ),
            (
                L("that’s a wrap (for today)",
                  ru: "that’s a wrap (на сегодня)",
                  de: "that’s a wrap (für heute)",
                  es: "that’s a wrap (por hoy)",
                  fr: "that’s a wrap (pour aujourd’hui)",
                  ja: "今日はラップ",
                  ko: "오늘은 wrap",
                  ar: "خلصت (لهاليوم)",
                  it: "that’s a wrap (per oggi)",
                  zhHans: "今天收工",
                  zhHant: "今天收工",
                  pt: "that’s a wrap (por hoje)"),
                L("see you tomorrow. don’t leave us on read.",
                  ru: "до завтра. не оставляй нас left on read.",
                  de: "bis morgen. lass uns nicht left on read.",
                  es: "hasta mañana. no nos dejes left on read.",
                  fr: "à demain. nous laisse pas left on read.",
                  ja: "また明日。既読スルーしないで。",
                  ko: "내일 봐. 읽씹하지 마.",
                  ar: "بشوفك بكرا. ما تخلينا left on read.",
                  it: "a domani. non lasciarci left on read.",
                  zhHans: "明天见。别已读不回。",
                  zhHant: "明天見。別已讀不回。",
                  pt: "até amanhã. não nos deixes left on read.")
            ),
            (
                L("goal done. soft threat cancelled",
                  ru: "цель done. мягкая угроза cancelled",
                  de: "ziel erledigt. soft threat cancelled",
                  es: "meta hecha. amenaza soft cancelled",
                  fr: "objectif fait. soft threat cancelled",
                  ja: "目標クリア。やさしい脅し解除",
                  ko: "목표 완료. 소프트 협박 취소",
                  ar: "الهدف خلص. التهديد اللطيف ملغي",
                  it: "obiettivo fatto. soft threat cancelled",
                  zhHans: "目标完成。温柔威胁取消",
                  zhHant: "目標完成。溫柔威脅取消",
                  pt: "objetivo feito. soft threat cancelled"),
                L("streak safe. vibes restored. go touch grass.",
                  ru: "серия в безопасности. вайбы восстановлены. иди touch grass.",
                  de: "serie sicher. vibes restored. geh touch grass.",
                  es: "racha a salvo. vibes restored. ve a touch grass.",
                  fr: "série safe. vibes restored. va touch grass.",
                  ja: "連続セーフ。バイブス回復。touch grassして。",
                  ko: "연속 안전. 바이브 복구. touch grass 해.",
                  ar: "السلسلة بأمان. الفايبس رجعت. روح touch grass.",
                  it: "serie al sicuro. vibes restored. vai a touch grass.",
                  zhHans: "连续安全。氛围恢复。去 touch grass。",
                  zhHant: "連續安全。氛圍恢復。去 touch grass。",
                  pt: "sequência segura. vibes restored. vai touch grass.")
            ),
            (
                L("plot twist: you actually finished",
                  ru: "плот твист: ты реально закончил",
                  de: "plot twist: du hast wirklich fertig",
                  es: "plot twist: de verdad terminaste",
                  fr: "plot twist: t’as vraiment fini",
                  ja: "どんでん返し：本当に終わらせた",
                  ko: "반전: 진짜 끝냄",
                  ar: "تويست: خلّصت فعلًا",
                  it: "plot twist: hai davvero finito",
                  zhHans: "剧情反转：你真做完了",
                  zhHant: "劇情反轉：你真做完了",
                  pt: "plot twist: acabaste mesmo"),
                L("receipts collected. tomorrow we threaten again. affectionately.",
                  ru: "receipts собраны. завтра снова пригрозим. с любовью.",
                  de: "receipts gesammelt. morgen drohen wir wieder. liebevoll.",
                  es: "receipts reunidos. mañana amenazamos otra vez. con cariño.",
                  fr: "receipts collectés. demain on menace encore. avec amour.",
                  ja: "証拠ゲット。明日また脅す。愛情込めて。",
                  ko: "영수증 수집됨. 내일 또 협박함. 애정으로.",
                  ar: "الإثباتات مجمّعة. بكرا منهدّد تاني. بحب.",
                  it: "receipts raccolti. domani minacciamo di nuovo. con affetto.",
                  zhHans: "收据到手。明天再威胁。带着爱。",
                  zhHant: "收據到手。明天再威脅。帶著愛。",
                  pt: "receipts recolhidos. amanhã ameaçamos outra vez. com carinho.")
            ),
        ])
    }



    static func pickEveningChat(word: String, translation: String) -> (title: String, body: String) {
        let titles: [[String: String]] = [
            L("night quest: one line",
              ru: "ночной квест: одна фраза",
              de: "nacht-quest: eine zeile",
              es: "misión nocturna: una línea",
              fr: "quête de nuit: une ligne",
              ja: "ナイトクエスト：ひとこと",
              ko: "나이트 퀘스트: 한 줄",
              ar: "مهمة ليلية: سطر",
              it: "quest notturna: una riga",
              zhHans: "夜间任务：一句",
              zhHant: "夜間任務：一句",
              pt: "quest noturna: uma linha"),
            L("say it before you doomscroll",
              ru: "скажи до думскролла",
              de: "sag’s vor dem doomscroll",
              es: "dilo antes del doomscroll",
              fr: "dis-le avant le doomscroll",
              ja: "ドゥームスクロール前に言って",
              ko: "둠스크롤 전에 말해",
              ar: "قولها قبل الدومسكرول",
              it: "dillo prima del doomscroll",
              zhHans: "刷到抑郁前说出来",
              zhHant: "刷到抑鬱前說出來",
              pt: "diz antes do doomscroll"),
            L("soft threat bedtime edition",
              ru: "мягкая угроза: bedtime edition",
              de: "soft threat bedtime edition",
              es: "amenaza soft bedtime edition",
              fr: "soft threat bedtime edition",
              ja: "やさしい脅し：就寝版",
              ko: "소프트 협박 취침판",
              ar: "تهديد لطيف نسخة نوم",
              it: "soft threat bedtime edition",
              zhHans: "温柔威胁：睡前版",
              zhHant: "溫柔威脅：睡前版",
              pt: "soft threat bedtime edition"),
            L("main character night scene",
              ru: "main character night scene",
              de: "main character night scene",
              es: "escena nocturna main character",
              fr: "scène de nuit main character",
              ja: "メインキャラ夜シーン",
              ko: "메인 캐릭터 나이트 씬",
              ar: "مشهد ليلي بروتاغونيست",
              it: "scena notturna main character",
              zhHans: "主角夜戏",
              zhHant: "主角夜戲",
              pt: "cena noturna main character"),
            L("one word before lights out",
              ru: "одно слово до lights out",
              de: "ein wort vor lights out",
              es: "una palabra antes de lights out",
              fr: "un mot avant lights out",
              ja: "消灯前に1語",
              ko: "불 끄기 전 단어 하나",
              ar: "كلمة قبل إطفاء الأنوار",
              it: "una parola prima di lights out",
              zhHans: "熄灯前一个词",
              zhHant: "熄燈前一個詞",
              pt: "uma palavra antes de lights out"),
        ]
        let bodies: [[String: String]] = [
            L("how would you drop «\(word)» in a chat? we’re listening.",
              ru: "как бы ты закинул «\(word)» в чат? мы слушаем.",
              de: "wie würdest du «\(word)» im chat droppen? wir hören zu.",
              es: "¿cómo dropearías «\(word)» en un chat? escuchamos.",
              fr: "comment tu dropperais «\(word)» dans un chat ? on écoute.",
              ja: "チャットで「\(word)」どう落とす？聞いてるよ。",
              ko: "채팅에 «\(word)» 어떻게 드롭할래? 듣고 있어.",
              ar: "كيف بترمي «\(word)» بالشات؟ عم نسمع.",
              it: "come dropperesti «\(word)» in chat? stiamo ascoltando.",
              zhHans: "你会怎么在聊天里甩出「\(word)」？我们听着。",
              zhHant: "你會怎麼在聊天裡甩出「\(word)」？我們聽著。",
              pt: "como dropavas «\(word)» num chat? estamos a ouvir."),
            L("«\(word)» — \(translation). use it once or we soft-threat again.",
              ru: "«\(word)» — \(translation). один раз — или снова мягкая угроза.",
              de: "«\(word)» — \(translation). einmal nutzen oder soft threat wieder.",
              es: "«\(word)» — \(translation). úsala una vez o amenaza soft otra vez.",
              fr: "«\(word)» — \(translation). une fois ou soft threat encore.",
              ja: "「\(word)」— \(translation)。一回使わないとまた脅す。",
              ko: "«\(word)» — \(translation). 한 번 쓰거나 소프트 협박 다시.",
              ar: "«\(word)» — \(translation). مرة أو تهديد لطيف تاني.",
              it: "«\(word)» — \(translation). usala una volta o soft threat di nuovo.",
              zhHans: "「\(word)」— \(translation)。用一次，不然再温柔威胁。",
              zhHant: "「\(word)」— \(translation)。用一次，不然再溫柔威脅。",
              pt: "«\(word)» — \(translation). usa uma vez ou soft threat outra vez."),
            L("reply in your head: \(word). scrolling can wait. no cap.",
              ru: "ответь в голове: \(word). скролл подождёт. no cap.",
              de: "antworte im kopf: \(word). scrollen kann warten. no cap.",
              es: "responde en la cabeza: \(word). el scroll puede esperar. no cap.",
              fr: "réponds dans ta tête : \(word). le scroll peut attendre. no cap.",
              ja: "頭の中で返信：\(word)。スクロールは待てる。マジ。",
              ko: "머릿속으로 답해: \(word). 스크롤은 기다려. 노캡.",
              ar: "جاوب براسك: \(word). السكرول فيو يستنى. no cap.",
              it: "rispondi in testa: \(word). lo scroll può aspettare. no cap.",
              zhHans: "脑子里回：\(word)。刷手机可以等。认真。",
              zhHant: "腦子裡回：\(word)。刷手機可以等。認真。",
              pt: "responde na cabeça: \(word). o scroll pode esperar. no cap."),
            L("plot twist night: use «\(word)» before bed. streak is watching.",
              ru: "ночной plot twist: используй «\(word)» до сна. серия смотрит.",
              de: "nacht-plot-twist: nutz «\(word)» vor dem schlafen. serie schaut zu.",
              es: "plot twist nocturno: usa «\(word)» antes de dormir. la racha mira.",
              fr: "plot twist de nuit : utilise «\(word)» avant de dormir. la série regarde.",
              ja: "夜のどんでん返し：「\(word)」を寝る前に。連続が見てる。",
              ko: "밤 반전: 자기 전에 «\(word)» 써. 연속이 보고 있음.",
              ar: "تويست ليلي: استعمل «\(word)» قبل النوم. السلسلة عم تراقب.",
              it: "plot twist notturno: usa «\(word)» prima di dormire. la serie guarda.",
              zhHans: "夜间反转：睡前用「\(word)」。连续打卡在看。",
              zhHant: "夜間反轉：睡前用「\(word)」。連續打卡在看。",
              pt: "plot twist noturno: usa «\(word)» antes de dormires. a sequência está a ver."),
            L("tiny chat scene with «\(word)». then touch grass (or sleep).",
              ru: "маленькая chat-сцена с «\(word)». потом touch grass (или сон).",
              de: "mini chat-szene mit «\(word)». dann touch grass (oder schlafen).",
              es: "mini escena de chat con «\(word)». luego touch grass (o dormir).",
              fr: "mini scène chat avec «\(word)». puis touch grass (ou dormir).",
              ja: "「\(word)」でちょっとチャット。そのあとtouch grass(か寝る)。",
              ko: "«\(word)»로 작은 채팅 씬. 그다음 touch grass (아니면 잠).",
              ar: "مشهد شات صغير مع «\(word)». بعدين touch grass (أو نوم).",
              it: "mini scena chat con «\(word)». poi touch grass (o dormire).",
              zhHans: "用「\(word)」来个小聊天。然后 touch grass(或睡觉)。",
              zhHant: "用「\(word)」來個小聊天。然後 touch grass(或睡覺)。",
              pt: "mini cena de chat com «\(word)». depois touch grass (ou dormir)."),
        ]
        let i = dayIndex
        return (t(titles[i % titles.count]), t(bodies[i % bodies.count]))
    }
}
